### ISSUE TITLE
VGA Tutorial Seems to be broken?

### ISSUE THREAD

**Issue by laserbeak** [SpinalHDL/SpinalHDL#10]
Hi,
Sorry for the noobie questions, but I don't know where else to get help. I've listed the code  I've made from the tutorial and the errors are at the bottom of the file.
http://pastebin.com/U4XcPx7R

**Comment by Dolu1990** [comment]
Hi,
It look like you need to update the spinal version that you have => 0.5.5
You can update in your build.sbt file with

libraryDependencies ++= Seq(
  "com.github.spinalhdl" % "spinalhdl-core_2.11" % "0.5.5",
  "com.github.spinalhdl" % "spinalhdl-lib_2.11" % "0.5.5"
)

**Comment by laserbeak** [comment]
Hi,
Yes was that and an issue stated in my pull request. 
Thanks for your help!
