### ISSUE TITLE
bitVectorWidthMax doesnt work in infer signals and ram

### ISSUE THREAD

**Issue by ghost** [SpinalHDL/SpinalHDL#1021]
![b518b9b3a36b7728be20411f9da4e48](https://user-images.githubusercontent.com/84612860/212791819-d7c92893-b56e-4118-93fe-3528c68e35f1.png)
should the second "Way too big signal" error  condition use bitVectorWidthMax instead of 4096?

**Comment by aiit-linry** [comment]
![image](https://user-images.githubusercontent.com/84612860/212793073-584a39df-2ea1-4506-b84b-2e1c369d5f23.png)

**Comment by calloftimereiver** [comment]
Is this bug fixed?

**Comment by Dolu1990** [comment]
Hi,

Yes i think it is.
