### ISSUE TITLE
use VCS+AxiMemorySim cause vpi error

### ISSUE THREAD

**Issue by aiit-linry** [SpinalHDL/SpinalHDL#1022]
![image](https://user-images.githubusercontent.com/84612860/212794727-9569e1c3-1428-4fbe-a175-67f4de252614.png)

**Comment by Readon** [comment]
I think it is similar with #973 where you can try "sbt clean" and rebuild again.

**Comment by aiit-linry** [comment]
> I think it is similar with #973 where you can try "sbt clean" and rebuild again.

I have tried “sbt clean” but still exist

**Comment by aiit-linry** [comment]
> I think it is similar with #973 where you can try "sbt clean" and rebuild again.

it appears in 1.8.0, in 1.7.3a its works ok

**Comment by Readon** [comment]
Yes, the get_time_precision is merged in 1.8.0. 

merlionfire has describe what he/she did in gitter.
```
 I am supposed to clean first otherwise .o is still old and doses NOT contain the expected native functions like get_time_precision*.

Eventually, I can run single-step VCS compilation based on local published version and succeed in simulation with fsdb file dumped.
```

**Comment by aiit-linry** [comment]
@numero-744 no, I have deleted all "*.o" file manually in my project and excuted "sbt clean", this question still here

**Comment by Readon** [comment]
> @numero-744 no, I have deleted all "*.o" file manually in my project and excuted "sbt clean", this question still here

How about clear the simulation dir, like simWorkspace?

**Comment by aiit-linry** [comment]
> > @numero-744 no, I have deleted all "*.o" file manually in my project and excuted "sbt clean", this question still here
> 
> How about clear the simulation dir, like simWorkspace?

done! Thats amazing, sorry for my stupid.

**Comment by Readon** [comment]
> > > @numero-744 no, I have deleted all "*.o" file manually in my project and excuted "sbt clean", this question still here
> > 
> > 
> > How about clear the simulation dir, like simWorkspace?
> 
> done! Thats amazing, sorry for my stupid.

We should add a tip on FAQ to Documentation, where the first steps suggested to people is "sbt clean" and "remove simulation directory" when people met errors with spinal.sim.vpi.

I just find the solution by review the code for vpi wrappers' generation.
