### ISSUE TITLE
Why there is no AXI4toapb3bridge lib

### ISSUE THREAD

**Issue by Amegodvivado** [SpinalHDL/SpinalHDL#1063]
Why there is no AXI4toapb3bridge lib but use AXI4sharedBridge, do we need to convert AXI4TOAxi4Share ourselves?

**Comment by Amegodvivado** [comment]
HOW to convert？

**Comment by Dolu1990** [comment]
Hi,

Using https://github.com/SpinalHDL/SpinalHDL/blob/6fba447046e0a846774a72b53676c5b318f9344f/lib/src/main/scala/spinal/lib/bus/amba4/axi/Axi4.scala#L207
You can do myAxi4Bus.toShared()  and then connect this to the AXI4sharedBridge

**Comment by Amegodvivado** [comment]
Thank you for your answer，I'm a newbie

**Comment by Dolu1990** [comment]
Yes ^^
Looks right to me :)

**Comment by Amegodvivado** [comment]
Thank you very much for your reply in your busy schedule. By the way, how to implement the Axi4ToAhblite3 Bridge (or other bus convert )? Currently, there is no lib in Spinal, no def in AXI4. Haha~

**Comment by Dolu1990** [comment]
Hmm i think currently there is nothing to bridge from AXI4 to AHBlite3
I think the only bridge for Axi4Toxxxx is to Apb3.

**Comment by Dolu1990** [comment]
Hmm i think currently there is nothing to bridge from AXI4 to AHBlite3
I think the only bridge for Axi4Toxxxx is to Apb3.

**Comment by Amegodvivado** [comment]
> Hmm i think currently there is nothing to bridge from AXI4 to AHBlite3
> I think the only bridge for Axi4Toxxxx is to Apb3.

Ok,thank you again for your answer

**Comment by Amegodvivado** [comment]
> Hmm i think currently there is nothing to bridge from AXI4 to AHBlite3
> I think the only bridge for Axi4Toxxxx is to Apb3.

Ok,thank you again for your answer
