### ISSUE TITLE
What are the differences between lib/sdr and lib/xdr? 

### ISSUE THREAD

**Issue by LurenAA** [SpinalHDL/SpinalHDL#1082]
1. What are the differences between lib/sdr and lib/xdr? Does lib/sdr only support SDRAM, while lib/xdr supports both SDRAM and DDRx SDRAM? 

2. Do lib/sdr and lib/xdr now only support a SDRAM chip, not a SDRAM memory module(such as MT16KTF1G64HZ - 8GB, a DDR3L SDRAM SODIMM)? 

I am a novice to SpinalHDL, I would be very grateful if you could help me. 😁

**Comment by Readon** [comment]
I also traced a little bits.
The definition of sdr's IO is as below.
<img width="630" alt="1681045493914" src="https://user-images.githubusercontent.com/3614708/230774310-b32fd14b-573e-4983-b60e-b97bfee01696.png">

Here it is for xdr:
<img width="610" alt="1681045369105" src="https://user-images.githubusercontent.com/3614708/230774334-8b58d082-4375-4dfd-8b4f-44d4dfac488d.png">

The most obvious difference is the ODT signal is introduced.
This signal is defined firstly while DDR2 standard.

**Comment by Dolu1990** [comment]
lib/sdr is SDRAM gen 1 only, while lib/xdr could "potentialy" target any DRAM tech, as long as there is a phy implemented for it.

Currently both were only used for regular chip. Not modules.
I guess as long as you use modules with single rank it could work ?

**Comment by andreasWallner** [comment]
@LurenAA Did that answer your question? If so, can we close this?
