### ISSUE TITLE
InOutWrapper TriState Tag Propagation?

### ISSUE THREAD

**Issue by kleinai** [SpinalHDL/SpinalHDL#1086]
I'm working on a design with an inout/tristate capable pin.  I've written my own set of tags for pin constraints.  I'm noticing tags on the tristate signal don't bubble up when using the `InOutWrapper`.  Is this something that might be useful as a feature?

Loose example:
```scala
case class Rgmii() extends Bundle with IMasterSlave {
  val TX = RgmiiTx()
  val RX = RgmiiRx()
  val MDIO = Mdio() // Provides tristate IO pin

  override def asMaster(): Unit = {
    out(TX)
    in(RX)
    master(MDIO)
  }
}
```
```scala
class TopLevel extends Component {
  val io = new Bundle {
    // ..snip..
    val rgmii = master(Rgmii())
  }

  // ..snip..
  io.rgmii.MDIO.IO.addTag(PinTag("C8")).addTag(PinStandardTag("LVCMOS18"))
}
```
Then in an app object:
```scala
  val report = SpinalVhdl(InOutWrapper(new TopLevel()))
```

I search for tagged IO with this, unless there's a better way.
```scala
  val pinConstraints = report.globalData.toplevel.getAllIo.flatMap { bt =>
    bt.getTag(classOf[PinTag]).map(t => t.getConstraintText(bt))
  }.flatten.mkString(System.lineSeparator())
```

**Comment by Dolu1990** [comment]
Hi,

Yes that could be usefull. We just need a way to specify which Tag need to be propagated, maybe by having the tags which need propagation extending a dedicated Trait ?
