### ISSUE TITLE
axi4Crossbar address out of range

### ISSUE THREAD

**Issue by ZhengJuzhong666** [SpinalHDL/SpinalHDL#1137]
Hello! I try to connect an axi bus to the slave side of a AxiCrossbar.  The address width is 32 bits.  When I allocate 2GiB of address space to this axi bus, there is no problem. It ranges from 0x80000000 to 0xFFFFFFFF.  But when I want to allocate 2560 MiB of address space from 0x60000000 to 0xFFFFFFFF for it, I get the “OUT OF RANGE CONSTANT” error.
This is my code：
~~~scala
  axi4Crossbar.addSlaves(
    io.highSpeedBus -> (0x60000000l, 2560 MiB)
  )
~~~

And this is the error：
![image](https://github.com/SpinalHDL/SpinalHDL/assets/127759020/6320a02e-a6dc-4b7c-8593-4a2b43a61e97)

When I change the range to 2559MiB, it works.  I don't understand why this problem occurs in AxiCrossbar, Could you help me? Thank you！

**Comment by ZhengJuzhong666** [comment]
Thank you， My SpinalHDL version is 1.8.0

**Comment by Dolu1990** [comment]
I think you need to update to 1.8.1, the fix is likely that one : 
https://github.com/SpinalHDL/SpinalHDL/commit/018e3128e4dec180e9faf4c7c35998d4133657cb

**Comment by ZhengJuzhong666** [comment]
Thank you！I will do the updata.
