### ISSUE TITLE
Axi4 support outstanding and out-of-order transmission

### ISSUE THREAD

**Issue by xie-1399** [SpinalHDL/SpinalHDL#1145]
Hi!
AXI bus supports out-of-order transmission and outstanding mechanism. Do you have any ideas on implementing these mechanisms in SpinalHDL?
Thank You :)

**Comment by Dolu1990** [comment]
the current blocks implemented in SpinalHDL about AXI4 support out of order answers between ID, but do not support beats of different burst to be interleaved.

What do you mean by "Do you have any ideas on implementing these mechanisms in SpinalHDL?" ?
