### ISSUE TITLE
Link lost for webinar

### ISSUE THREAD

**Issue by franktaTian** [SpinalHDL/SpinalHDL#1157]
Hi,
   I found[Spinal Webinar]( https://github.com/SpinalHDL/SpinalHDL/discussions/952),it is intereting!But the link [(https://datenlord.github.io/en/spinal.html](https://datenlord.github.io/en/spinal.html) is lost.
Any help?

**Comment by Readon** [comment]
@pwang7 may be Dr. Wang could help.

**Comment by Dolu1990** [comment]
Here is the youtube channel with the video : 
https://www.youtube.com/@datenlord

**Comment by pwang7** [comment]
let me check

**Comment by andreasWallner** [comment]
@pwang7 I assume you found what you were looking for, feel free to reopen if not
