### ISSUE TITLE
there is a bug in the read transaction of AxiLite4 Regif

### ISSUE THREAD

**Issue by cheerryio** [SpinalHDL/SpinalHDL#1163]
My simulation result about axilite4 regif is below
![image](https://github.com/SpinalHDL/SpinalHDL/assets/50071687/787e6b34-80ed-4f45-9a1d-a05484b1339f)

I have generated a axilite4 read transaction on address 0x08. The `arvalid` and `arready` has successfully handshaked. But the rdata just has kept one cycle and then changed before `rvalid` and `rready` has handshaked.

I traced the source code of axilite4 regif and found this code snipet: 
```
  private def readGenerator() = {
    when(askRead){
      switch (readAddress()) {
        RegInsts.foreach{(reg: RegInst) =>
          if(!reg.allIsNA){
            is(reg.addr){
              readData  := reg.readBits
              readError := Bool(reg.haveWO)
            }
          }
        }
        default{
          //Reserved Address Set False, True is too much strict for software
          readData  := readDefaultValue
          if(withStrb) {
            readError := False
          } else {
            val alignreadhit = readAddress.take(log2Up(wordAddressInc)).orR
            readError := Mux(alignreadhit, True,  False)
          }
        }
      }
    }.otherwise{
      //do not keep readData after read for the reason of security risk
      readData  := readDefaultValue
      readError := False
    }
  }
```

The change of the code was introduced with #1039 . Only when `askRead` is present can true data presents, but `askRead` just keeps one clock cycle and `readData` disapears before `rvalid` and `rready` handshakes. I believe there is something wrong, or you can correct me.

@jijingg

**Comment by cheerryio** [comment]
I found this problem may be the same as #1159

**Comment by jijingg** [comment]
> askRead
I traced the source code of axilite4 regif and found this code snipet:
```
  private def readGenerator() = {
    when(askRead){
      switch (readAddress()) {
        RegInsts.foreach{(reg: RegInst) =>
``` 
This part is a public component, not the problem of this part. The meaning of askRead is fixed and needs apb/axi-lit4/AHB to match it.
so , the isuue maby here , we shold update `val askRead   = axiAr.valid` define in 
https://github.com/SpinalHDL/SpinalHDL/blame/1a714e3370d83090eb7be2bd4faf2a808c2c2cb5/lib/src/main/scala/spinal/lib/bus/regif/BusIfAdapter/AxiLite4BusInterface.scala#L52
in addition the AXI4-Lite for regif without sufficient verification, I suggest you use APB4's regif interface, which has been fully validated on our commercial chip project
