### ISSUE TITLE
when I update to 1.9.0  ,class cpu.CibGlb cannot be cast to class cpu.LocalBusInterface (cpu.CibGlb and cpu.LocalBusInterface are in unnamed module of loader 'app')

### ISSUE THREAD

**Issue by Mido-sun** [SpinalHDL/SpinalHDL#1173]
> case class LocalBusInterface(bus:LocalBus, override val readSync: Boolean= true, regPre: String = "")(implicit moduleName: ClassName) extends BusIf{

and instance in another module 

>   val busIf = LocalBusInterface(io.cpu_intf)

**Comment by andreasWallner** [comment]
Since from what you posted it's unclear what the types of the classes involved are, where the error occurs and since most of the classes are custom we can't really help with what you have given us.
Please try to make a small example that reproduces the error, that we can also run.

**Comment by Mido-sun** [comment]
I back spinal version 2-11-1.8.2  from 2-12-1.8.2   it is ok now
