### ISSUE TITLE
SpinalHDL 1.9.0 BufferCC is not Forward compatibility

### ISSUE THREAD

**Issue by xiaochuang-lxc** [SpinalHDL/SpinalHDL#1174]
As the depth in BufferCC is changed to Option[Int] in 1.9.0 ,it's not forward compatibility.
My Code BufferCC(a,True,3) will generate an error in 1.9.0
It's better to add a new apply for it instead of replacing the old method

**Comment by Dolu1990** [comment]
Ahhh yes, you are right, we should add a new apply.
