### ISSUE TITLE
How to get init value of Reg type

### ISSUE THREAD

**Issue by kellenwang1017** [SpinalHDL/SpinalHDL#1176]
I wanna create a bunch of Regs in serial that follows a certain Reg R (just to create N clock delayed copy of R), and copy the init value of R as their own init value. I checked the code of Reg.init(), it uses assignInit() to initialise the Reg, and there's no public val or any other method provided to fetch the value once passed to init() method. Any suggestion?

**Comment by likewise** [comment]
Hmm, is `Delay()` what you want?

**Comment by Dolu1990** [comment]
There is currently no real API to retreive the value used to init something.
But it can be done : 

```scala
    val miaou = Reg(UInt(8 bits)) init(42)
    
    miaou.foreachStatements{
      case s : InitAssignmentStatement => {
        println(s)
        s.source match {
          case bt : UInt => {
            println(bt)
            bt.foreachStatements{
              case s : DataAssignmentStatement => {
                println(s)
                s.source match {
                  case lit : UIntLiteral => {
                    println(lit.value)
                  }
                }
              }
            }
          }
        }
      }
      case _ =>
    }
    
    will print 
    (toplevel/miaou :  UInt[8 bits]) := (U"101010" 6 bits)
    (U"101010" 6 bits)
    (U"101010" 6 bits) := (U"101010" 6 bits)
    42
```

**Comment by kellenwang1017** [comment]
Dolu you are the best!!!!!!!!!!!!!!!!!
