### ISSUE TITLE
VCS runFlags unable to pass into the simulation

### ISSUE THREAD

**Issue by raochl** [SpinalHDL/SpinalHDL#1190]
There is a `runFlags` in VCSFlags which is used to configure the simulation process. But after the rework of the VCS Flags on PR #911 , the `runFlags` in testbench as following cannot pass into the simulation.
```scala
  val flags = VCSFlags(
    compileFlags = List(
      "-kdb"
    ),
    elaborateFlags = List("-kdb"),
    runFlags = List("-l sim.log")
  )
```

The simulation log:
![image](https://github.com/SpinalHDL/SpinalHDL/assets/38033760/eb9cc8fe-c721-4edd-a4df-02884e476655)

As we can see in the picture, the info of the simulation command is just `[SIMV] ./directionEnc` which did not contain the `-l sim.log` option.

I found it is because the `runFlags` belongs to `VCSFlags` and does not pass to `VpiBackandConfig.runFlags`. Therefore in Line 360:
https://github.com/SpinalHDL/SpinalHDL/blob/09e69e56dd4744abbb284b80a9c7cdd4699cc6f3/sim/src/main/scala/spinal/sim/VCSBackend.scala#L359-L367

the `config.runFlags` contains nothing. So there is nothing after the simulation execute command.

**Comment by wswslzp** [comment]
Sorry for late reponse, bug fix in #1202
