### ISSUE TITLE
PackedBundle BUG?

### ISSUE THREAD

**Issue by dreamflyings** [SpinalHDL/SpinalHDL#1204]
@Dolu1990 Hello~   
Is there a problem with the following code line logic?
[bug line](https://github.com/SpinalHDL/SpinalHDL/blob/2fdc3aadfc859bbfcf0fb559658606f3dbe4f705/lib/src/main/scala/spinal/lib/PackedBundle.scala#L60) 
Should this line lastPos = r.high be changed to lastPos = r.high + 1?

**Comment by Dolu1990** [comment]
Hi,

Looking at "downto (lastPos)"  =>  yes, likely, but i don't know much about PackedBundle at all XD

**Comment by andreasWallner** [comment]
@dokleina could you have a look at this?

**Comment by dokleina** [comment]
Hey all,

I agree that this is broken. The `lastPos` probably should have been named `nextPos` instead with a `+1` to the value.

I've got a branch with a potential fix, but it'll be a bit until I get complete test coverage.
