### ISSUE TITLE
Simulation fails when using Verilator of new version which requires C++14 standard

### ISSUE THREAD

**Issue by ZimingYuan** [SpinalHDL/SpinalHDL#1209]
When using Verilator of new version (such as 5.016), simulation fails and complains something like

```
[info] In file included from /usr/local/share/verilator/include/verilated.h:937,
[info]                  from VLinear___024root__DepSet_h572e5853__3.cpp:5:
[info] /usr/local/share/verilator/include/verilated_types.h: In function 'constexpr IData VL_CLOG2_CE_Q(QData)':
[info] /usr/local/share/verilator/include/verilated_types.h:85:1: error: body of 'constexpr' function 'constexpr IData VL_CLOG2_CE_Q(QData)' not a return-statement
[info]    85 | }
[info]       | ^
```

It seems that Verilator requires using C++14 standard to compile the simulation files. However, the compile options are hard coding in `sim/src/main/scala/spinal/sim/VerilatorBackend.scala`. Is it possible to change compile options by user?

**Comment by andreasWallner** [comment]
I'm currently updating to check, still one question: do you pass any additional parameters to verilator? I've been using `5.005` which should have the same C++ requirements, which worked.

**Comment by andreasWallner** [comment]
Just updated to `5.0017` with which I can reproduce the issue.
