### ISSUE TITLE
Is there any code in the repository that tests Xdr.scala and determines whether it can run properly on DDR3 and DDR2 chips?

### ISSUE THREAD

**Issue by LurenAA** [SpinalHDL/SpinalHDL#1221]
The file SdramXdrSdrSpinalSim.scala includes tests for Xdr.scala. However, the controller in that file is connected to RtlPhy, which itself does not connect to simulation files for DDR SDRAM. It only verifies the correctness of controller operations through a series of checks. So, is there any code available that validates the controller's correctness by connecting it to a real DDR3 SDRAM simulation file, such as XilinxS7Phy + Micron DDR3 SDRAM?

thank you!

**Comment by Dolu1990** [comment]
Hi,
Hmm it was a very long time ago, i guess i manualy did simulations on vivado to check that the XilinxS7Phy was behaving as expected. As there is very few states in it, it is kinda of easy to manualy do.

I don't have any trace of it anymore XD
