### ISSUE TITLE
Error: <error value core is not a member of spinal>#Int

### ISSUE THREAD

**Issue by LurenAA** [SpinalHDL/SpinalHDL#1222]
I have a BlackBox like this:

![image](https://github.com/SpinalHDL/SpinalHDL/assets/45759613/c09c7696-3450-47dc-a079-763e513a5b40)

when I try to initialize it, it show this:

![image](https://github.com/SpinalHDL/SpinalHDL/assets/45759613/fdb24945-1f5f-4204-9d00-68ada8c8438b)

Is there some thing wrong ? thank you!

**Comment by Dolu1990** [comment]
Hi,

You need to add the 5 parameter value i guess ?
