### ISSUE TITLE
Vec init(0)

### ISSUE THREAD

**Issue by zeroday-engineer** [SpinalHDL/SpinalHDL#127]
I've been having a hard time finding the proper syntax/preferred method of initializing a Vec(Reg(Uint())), currently using the map function. Is init extended for arrays/multidimensional representations?

**Comment by Dolu1990** [comment]
Hi,

```scala
  class TopLevel extends Component {
    val x = Vec(Reg(UInt(8 bits)) init(0), 4)
    val y = Vec(Reg(UInt(8 bits)), 4)
    y.foreach(_ init(0))
    
    //Just to avoid having reseted only flops
    x := y
    y := x
  }
```

Should be applicable to more dimension :)

**Comment by zeroday-engineer** [comment]
WoW, that's simple. Thank you for your help. Is there a Discord channel or some other chat setup for general questions? I kinda feel bad about creating an issue every time I'm stuck :)

**Comment by Dolu1990** [comment]
Sure, there is : 
https://gitter.im/SpinalHDL/SpinalHDL
No problems ^^
