### ISSUE TITLE
RegIf doesn't support fields of SpinalEnum type

### ISSUE THREAD

**Issue by louiecaulfield** [SpinalHDL/SpinalHDL#1286]
When trying to create a field of for a SpinalEnum type, the creation fails at [RegInst.scala#142](https://github.com/SpinalHDL/SpinalHDL/blob/eb5a3a705ab25bfc6e236a51352f02934c22572b/lib/src/main/scala/spinal/lib/bus/regif/RegInst.scala#L142)

I'm not familiar enough (yet) with Spinal's internals to estimate the amount of work to implement this, but it would make my code much more beautiful if SpinalEnums are supported :-)

**Comment by Dolu1990** [comment]
@jijingg

**Comment by jijingg** [comment]
Sorry for the late reply. It shouldn't be difficult to support ENUM, but what I would like to ask is, in what scenario will regef be used in registers? Can you give me a real example， @louiecaulfield
