### ISSUE TITLE
How can I use "dophase" to check some diy list?

### ISSUE THREAD

**Issue by Mido-sun** [SpinalHDL/SpinalHDL#1291]
some example plz  scala rookie!!!

**Comment by Dolu1990** [comment]
Hi,

What is dophase ?
You mean how to add a custom transformation phase  in SpinalHDL ?

**Comment by Mido-sun** [comment]
> Hi,
> 
> What is dophase ? You mean how to add a custom transformation phase in SpinalHDL ?

yes

**Comment by Dolu1990** [comment]
Have you seen this hidden part of the doc : 
https://spinalhdl.github.io/SpinalDoc-RTD/master/SpinalHDL/Developers%20area/spinalhdl_datamodel.html#exploring-the-datamodel

**Comment by Mido-sun** [comment]
> Have you seen this hidden part of the doc : https://spinalhdl.github.io/SpinalDoc-RTD/master/SpinalHDL/Developers%20area/spinalhdl_datamodel.html#exploring-the-datamodel

No ,I will read it now . Thank You

**Comment by yportne13** [comment]
a small demo: https://github.com/yportne13/SpinalMemBist/blob/master/src/scala/main/resize.scala

**Comment by andreasWallner** [comment]
Since this is two weeks old I guess we can consider this answered.
