### ISSUE TITLE
The wave reload question of VCS simulation

### ISSUE THREAD

**Issue by xie-1399** [SpinalHDL/SpinalHDL#1295]
HI !
    I meet a question when using the VCS simulation，Here is my question：
    using "shift + L" in the VCS can reload the wave. However, when I recompile the test , and I want to reload the wave in the VCS，the error occurred：

![f6078ed078e129214e574f1233b141f](https://github.com/SpinalHDL/SpinalHDL/assets/62367053/32be927a-9c80-4d9a-abab-e124150ba0e5)

what should I do if I want to reload the wave in VCS after recompile the test? Thank You

**Comment by Dolu1990** [comment]
@wswslzp (Let's me know if you don't want pings, i'm now just unpilling all the email i have and try to notify the poeple related to specific issues :))

**Comment by wswslzp** [comment]
Sometime, Verdi cannot reload the waveform is expected since the KDB/waveform are removed and regenerated while Verdi is openning for some specific Verdi/VCS version.

**Comment by xie-1399** [comment]
how to stop the KDB/waveform regenerated when starting the simulation each time?

**Comment by wswslzp** [comment]
I think there's no way to prevent from regenerating KDB. SpinalHDL remove the sim workspace each time you recompile tests by default as I remembered.

**Comment by xie-1399** [comment]
Thank You !
