### ISSUE TITLE
Pipeline API `throwWhen(usingReady = true)` doesn't drop transaction when conflicting with prior `halt` 

### ISSUE THREAD

**Issue by 64** [SpinalHDL/SpinalHDL#1298]
The 'throw' and 'halt' operations seem to conflict with eachother when they are executed in the same cycle.

In the decode stage, I put some fake hazard logic:

```
    haltWhen(isValid && execute.isValid && IS_ADD && execute(IS_JUMP))
```

and in the execute stage, there is flushing logic that calls `throwWhen`:

```
    val flush = False
    for (stage <- List(fetch, decode)) {
      stage.throwWhen(flush, usingReady = true)
    }
```

This causes the decode.up to not be properly cleared and a buggy transaction is generated, as evidenced by the following test failure:

```
    mem.setBigInt(0, nop())
    mem.setBigInt(1, nop())
    mem.setBigInt(2, nop())
    mem.setBigInt(3, jump(0x1))
    mem.setBigInt(4, add(0x4))

    SimTimeout(1000)
    dut.clockDomain.forkStimulus(10)

    def checkNextPc() = {
      dut.clockDomain.waitSamplingWhere(dut.alu.retire.valid.toBoolean)
      dut.alu.retire.payload.toInt
    }
    assert(checkNextPc() == 0)
    assert(checkNextPc() == 1)
    assert(checkNextPc() == 2)
    assert(checkNextPc() == 3)
    assert(checkNextPc() == 1) // fails here: next PC = 4
    assert(checkNextPc() == 2)
    assert(checkNextPc() == 3)
    assert(checkNextPc() == 1)
```

We can see this in the waves:

![image](https://github.com/SpinalHDL/SpinalHDL/assets/6154626/e14c52c4-adc0-4230-8848-eaf2564b1740)

Note that if the `usingReady = true` is changed to `usingReady = (stage == fetch)` (setting `false` on decode), then the test passes and the waveform shows that the transaction is correctly forgotten:

![image](https://github.com/SpinalHDL/SpinalHDL/assets/6154626/302e95e7-8a7c-4b42-922b-e44f5d16938a)

# Reproduction

Full repro can be found here: https://github.com/SpinalHDL/SpinalTemplateSbt/compare/master...64:SpinalTemplateSbt:repro-pipeline-bug

Run with `sbt "runMain projectname.MyTopLevelSim"`

# Expected Behaviour

Not honestly sure -- I would expect the `throw` to 'win' against the `halt` since it's called later. Or maybe it is just a user error to do this on the same cycle and it should be documented as such?

Either way, it's pretty surprising that `usingReady` should make a difference here!

**Comment by Dolu1990** [comment]
Thanks ^^
Yes, throw should win against halt, and that wasn't the case of the "ignoreReady" primitive. Your test now pass with dev branch.
