### ISSUE TITLE
Wishbone BusIf SEL usage

### ISSUE THREAD

**Issue by jdavidberger** [SpinalHDL/SpinalHDL#1311]
I think there is a bug [here](https://github.com/SpinalHDL/SpinalHDL/blob/dev/lib/src/main/scala/spinal/lib/bus/regif/BusIfAdapter/WishboneBusInterface.scala#L37) but it's possible I'm reading the wishbone spec wrong.

[From here](https://cdn.opencores.org/downloads/wbspec_b3.pdf#page=66) it seems like the SEL line is a byte select / partial word mechanism not a chip select like it looks like in the code. 

It doesn't look like BusIf really supports partial word writes, so perhaps the easiest thing is to just remove the use of SEL in that class altogether. I can make this change but I wanted to make sure I wasn't misunderstanding anything before doing so.

**Comment by Dolu1990** [comment]
Hi,

Yes you are right.

> so perhaps the easiest thing is to just remove the use of SEL

Yes. PR welcome :)

Thanks
