### ISSUE TITLE
Feature: Allow to pass flags to verilator when compiling a simulation

### ISSUE THREAD

**Issue by dlobato** [SpinalHDL/SpinalHDL#139]
Currently there's no way to pass extra options to verilator, for instance a library path. It would be great to have a option to pass extra flags.

Seems like verilator command is built here and there's no way to pass extra flags: https://github.com/SpinalHDL/SpinalHDL/blob/0047f3879f0b8b5fab914a340abea7f7f76dea61/sim/src/main/scala/spinal/sim/VerilatorBackend.scala#L333

**Comment by dlobato** [comment]
I've implemented extraFlags for verilator:
https://github.com/SpinalHDL/SpinalHDL/pull/140

**Comment by Dolu1990** [comment]
Thanks for the fix
