### ISSUE TITLE
Nesting SlowAreas produces unexpected results

### ISSUE THREAD

**Issue by louiecaulfield** [SpinalHDL/SpinalHDL#1424]
I'm using `ClockDomain.SlowArea` to reduce my clock frequency. I am however doing this in 2 steps: Starting from let's say 90MHz I generate a slower clock domain at 30MHz, which I then want to reduce to 5MHz. I generate a `SlowArea` within a `SlowArea`.

I finally generate the actual clock signals running at 15MHz / 2.5MHz by having always-toggling registers.

What I observe is that the slowest clock has multiple edges at each transition.
![image](https://github.com/SpinalHDL/SpinalHDL/assets/6247850/517159bc-d471-47a8-8867-f99a815e9e00)

The code to generate the simulation is

```scala
package cores.utils

import spinal.core._
import spinal.lib._
import spinal.core.sim._

case class ClockTest(freq : HertzNumber) extends Component {
  val io = new Bundle {
    val clk_15000 = out port Bool
    val clk_2500 = out port Bool
  }

  val area_div_3 = new SlowArea(3) {
    io.clk_15000 := Reg(Bool).toggleWhen(True)
    val area_div_9 = new SlowArea(3) {
      io.clk_2500 := Reg(Bool).toggleWhen(True)
    }
  }
}

object ClockTestSim extends App {
  SimConfig.withFstWave.compile(new ClockTest(90.MHz)).doSim{ dut =>
    dut.clockDomain.forkStimulus(dut.freq)
    dut.clockDomain.assertReset()
    dut.clockDomain.waitEdge(5)
    dut.clockDomain.deassertReset()
    dut.clockDomain.waitActiveEdge(400)
  }
}

```

**Comment by Dolu1990** [comment]
Hi,

Just fixed it, thanks ^^
