### ISSUE TITLE
RFE: Option to create unique auto-created signals names 

### ISSUE THREAD

**Issue by tomverbeure** [SpinalHDL/SpinalHDL#144]
See the following comment, and some later comments in the discussion as well:
https://github.com/SpinalHDL/SpinalHDL/issues/133#issuecomment-415476384

**Comment by Dolu1990** [comment]
What about adding the name of the module definition ? _zz_StreamFifo_X_ ?
(As an generation option)

**Comment by tomverbeure** [comment]
That's even better, and probably easier to implement? 

Tom

**Comment by Dolu1990** [comment]
Added in the dev branch, you have to set the SpinalConfig anonymSignalUniqueness flag to have the feature.

**Comment by Dolu1990** [comment]
And yes, easier to implement ^^

**Comment by tomverbeure** [comment]
Works like a charm. I love it!

But I didn't have to set the `anonymSignalUniqueness` flag. It worked out of the box.

Tom

**Comment by Dolu1990** [comment]
Fixed ^^
