### ISSUE TITLE
How about ignore the clone error while using generate in insert of Node.

### ISSUE THREAD

**Issue by Readon** [SpinalHDL/SpinalHDL#1464]
I have to create some logic by options so that following code might appear often.
``` Scala
val aNode = new Node {
     val data = insert(opts generate UInt(20 bits))
}

val bNode = new Node {
     val result = UInt(20 bits)
     if (opts) result := aNode.data()
}
```

The existing implementation could report "Exception in thread "main" java.lang.NullPointerException: Cannot invoke "spinal.core.Data.clone()" because "that" is null", because of the aNode.data is null while opts is false.

Or is there any other better way?

**Comment by Dolu1990** [comment]
Hi,

> aNode.data()

This is not correct.
aNode.data is a Payload, if you call its apply() function, it will create a new unconnected instance of the same data type.

What's about : 

```scala
val aNode = new Node {
     val data = opts generate insert(UInt(20 bits))
}

val bNode = new Node {
     val result = UInt(20 bits)
     if (opts) result := aNode.data
}
```
 
 ?
 
 There is also another alternative which, depending the scale of what you do can scale well : 
 
 
 ```scala
val aNode, bNode = new Node()
val result = UInt(20 bits)
val optsLogic = opts generate new Area{
  val onA = new aNode.Area{
    val data = insert(UInt(20 bits))
  }
  val onB = new bNode.Area{
    result := aNode.data
  }  
}
 ```
