### ISSUE TITLE
no waveforms displayed when using xsim

### ISSUE THREAD

**Issue by shjdgwj** [SpinalHDL/SpinalHDL#1496]
When simulating using the XSIM as backend, no waveforms displayed after  opening the wdb file
![image](https://github.com/user-attachments/assets/8ffdc66c-21b1-473d-98dc-0e0013583b4f)
But it seems like the simulation is done successfully because there debug info can be seen in the console.
![image](https://github.com/user-attachments/assets/b2722c72-de8b-48f9-ba6e-a9566ab062ce)
And there isn't any problem when I use Verilator as backend
I don't know how to solve this problem. The simulation code is like:
```
   def spinal = SpinalConfig(
      targetDirectory = "hw/gen",
      defaultConfigForClockDomains = ClockDomainConfig(
        resetActiveLevel = LOW
      ),
      onlyStdLogicVectorAtTopLevelIo = true
    )
    def sim: SpinalSimConfig = SimConfig.withConfig(spinal).withXSim.withXilinxDevice("xczu48dr-fsvg1517-2-e")
...
    dut.doSim("axis_vfifo_sim", 1145141) {
...
}
```

**Comment by shjdgwj** [comment]
[axi_vfifo.zip](https://github.com/user-attachments/files/16443769/axi_vfifo.zip)
Here's my wdb file

**Comment by aureoleday** [comment]
Same problem. The simulation process seems OK, but the generated wdb file has no waveform data inside

**Comment by aureoleday** [comment]
Solved! Need to add .withWave in sim

**Comment by Dolu1990** [comment]
Hoooo nice catch XD
Nice ^^

**Comment by shjdgwj** [comment]
> Solved! Need to add .withWave in sim

Thank you very much! It works!
