### ISSUE TITLE
Vivado/Vitis post simulation

### ISSUE THREAD

**Issue by yao-baijian** [SpinalHDL/SpinalHDL#1531]
Hi

Is there any way to perform post implementation simulation on Vivado using SpinalHDL as simuation source? Or I have to write a new testbench?

Best

**Comment by Dolu1990** [comment]
Hi,

Vivado can't use SpinalHDL as simulation source, but there is a XSIM backend in SpinalHDL, so SpinalSim may be able to use XSim to run simulations.

**Comment by yao-baijian** [comment]
Hi Dolu,

Is there any way to transfer SpinalHDL into C or C++ testbench ?

**Comment by Dolu1990** [comment]
Hi,
SpinalHDL testbench can't be translated into C/C++ automaticaly.
They use Scala runtime.
