### ISSUE TITLE
StreamFork2.takes has a small mistake

### ISSUE THREAD

**Issue by ramielkhatibPQS** [SpinalHDL/SpinalHDL#1542]
https://github.com/SpinalHDL/SpinalHDL/blob/bc486f691378d05edb83c00ce9487057d9c68859/lib/src/main/scala/spinal/lib/Stream.scala#L1020

Both values of the tuple are using `forks._1`. The second one should be `forks._2` like below:

```scala
 val outputs = (forks._1.takeWhen(take0), forks._2.takeWhen(take1)) 
```

**Comment by Dolu1990** [comment]
Thanks ^^

Fix pushed in dev
