### ISSUE TITLE
Issue with component naming 

### ISSUE THREAD

**Issue by g0t00** [SpinalHDL/SpinalHDL#1551]
The fix for #1020 commit id 1c25b6c482e9e46f47b12601a75a64bc47ccb93b has introduced some issue with naming of components.
We get a component without a name/label emitted to the rtl. 

I now spend a while trying to extract a MWE but fail to do so...
But the problem always appears when I instantiate a StreamCCByToggle component while calling rework on a existing component. This makes a BufferCC be instantiated that does not get a name. (I think from calling `outputClock.withOptionalBufferedResetFrom`).
As I use the getRtlPath function to generate SDC constraints the label need to be deterministic (and not empty).

I do not fully unerstand what happen in `PhaseAllocateNames` and the change seems minimal.
I tried changing ` for (c <- componentsReversed)` to ` for (c <- componentsReversed.reverse)`  (the second loop) this seems to fix the issue. But not sure if this is actually correct...

If required I can spend more time trying to extract a code example, but the bug seems to be rather finicky.

**Comment by Dolu1990** [comment]
Hi,

Hmm, realy weird, as you say the changes are very minimal.

> We get a component without a name/label emitted to the rtl.

So, an empty string ? ""

If in anyway you can send me a case for me to reproduce, i could try to breakpoint the issue and figure it out.
Doesn't need to be a minimal example.
