### ISSUE TITLE
Physical Number representation wrong on Scala 2.13

### ISSUE THREAD

**Issue by Readon** [SpinalHDL/SpinalHDL#1559]
Scala 2.13's f-string parser would not call formatTo function in Formattable. 
This lead following lines failed.
``` scala
assert(f"${HertzNumber(5123000)}" == "5.123 MHz")
assert(f"${HertzNumber(5123000)}%s" == "5.123 MHz")
assert(f"${HertzNumber(5123000)}%S" == "5.123MHz")
.....
``` 

Also fails the test spinal.core.PhysicalNumbers

**Comment by Readon** [comment]
@andreasWallner Can you have a look at it? the test on 2.13 is also in PR #1558

**Comment by andreasWallner** [comment]
I'll have a look, wondering how that ever worked then/when it broke...

**Comment by Dolu1990** [comment]
@andreasWallner A toke a little look, that is realy weird, seems like string interpolation doesn't trigger in the same way between 2.13 and 2.12 XD

**Comment by andreasWallner** [comment]
It's interesting since I did use that with a 2.13 version in the past...

**Comment by Readon** [comment]
> @andreasWallner A toke a little look, that is realy weird, seems like string interpolation doesn't trigger in the same way between 2.13 and 2.12 XD

In 2.13 the Scala community refacted the implementation of f-interpolator.

**Comment by Readon** [comment]
What does this used for? If it is really important, create a standalone custom interpolator like p-interpolator might be a good solution.

**Comment by Readon** [comment]
@andreasWallner How about move to fp-interpolator? #1561
