### ISSUE TITLE
FSM StateDelay and Timeout Rounding Issues

### ISSUE THREAD

**Issue by mrberman87** [SpinalHDL/SpinalHDL#1588]
In the [FSM StateDelay](https://github.com/SpinalHDL/SpinalHDL/blob/8ee0e9c942676fd740b22c888110f9fa696735da/lib/src/main/scala/spinal/lib/fsm/State.scala#L234) and [Timeout](https://github.com/SpinalHDL/SpinalHDL/blob/8ee0e9c942676fd740b22c888110f9fa696735da/lib/src/main/scala/spinal/lib/Utils.scala#L652), the arithmetic used does a truncation type rounding as they are kept as integer values.  When doing timing that requires a Minimum amount of time, this can lead to issues.  This is somewhat resolved in a few place in simulation code like [here](https://github.com/SpinalHDL/SpinalHDL/blob/8ee0e9c942676fd740b22c888110f9fa696735da/core/src/main/scala/spinal/core/sim/package.scala#L215), but forcing these to round up could break existing code.

I can add changes to fix this, but I would like some direction on how to best do so.  Here are my thoughts on how to resolve this:
1. Change the rounding in FSM State and Timeout to always just round up (potentially breaking existing code).
2. Add an overloaded function that takes a BigDecimal Rounding Type that can be used to round how the user sees fit.
3. Add new methods that somehow state minimum timing in their name, like "StateDelayMin" and "TimeoutMin".

What do you suggest?

**Comment by Dolu1990** [comment]
Hi, 

Right. hmmmm i agree that rounding up by default is the most sane thing to do.
It may break some code, but it seems very unlikely to me ? I would be more worry about the existing broken code where people expect that minimal delay, but in it isn't.

So i would be fine with implementing number 1)
