### ISSUE TITLE
Add asCloneOf method to Data type

### ISSUE THREAD

**Issue by typingArtist** [SpinalHDL/SpinalHDL#187]
When you need to convert a hardware instance to another type and return that one, you currently have to perform the following steps:

```scala
val newObj = cloneOf(anotherType)
newObj.assignFromBits(someObj.asBits) // this returns Unit
newObj // return newObj
```

A streamlined version of that could be used like that:

```scala
someObj.asCloneOf(anotherType) // performs cloneOf, asBits and assignFromBits and returns the new instance
```

**Comment by Dolu1990** [comment]
Why not just : 

xxx.as(yyy) ?

**Comment by Dolu1990** [comment]
Or xxx.asDataOf(yyy)

**Comment by typingArtist** [comment]
Let’s take ```.as()``` for a first attempt. I’ll fix the PR.
