### ISSUE TITLE
spinal.core.Trait.scala: addTags iterates over wrong tags collection

### ISSUE THREAD

**Issue by dronox** [SpinalHDL/SpinalHDL#198]
Hi @Dolu1990,

in spinal-core 1.3.1 (2.12 version) there is a small bug in line 565 of spinal.core.Trait. Instead of iterating over `tags` you iterate over `spinalTags` for adding tags which leads to tags not getting added, here.

Kind Regards,
Dustin

**Comment by Dolu1990** [comment]
Thanks ^^
Fixed :D

**Comment by dronox** [comment]
No issue, just using addTag instead of addTags currently ;)

**Comment by dronox** [comment]
Thx!
