### ISSUE TITLE
Bring the VexRiscv Quine–McCluskey into the Spinal lib

### ISSUE THREAD

**Issue by Dolu1990** [SpinalHDL/SpinalHDL#204]

**Comment by numero-744** [comment]
Isn't it too big or specialized to go into `spinal.lib`?

**Comment by Dolu1990** [comment]
No no, it is fairly simple.
It can be closed, as already merged : 
https://github.com/SpinalHDL/SpinalHDL/blob/dac69e9041b2c5ccabdd5bff79d49e20a2fcf093/lib/src/main/scala/spinal/lib/logic/Symplify.scala

**Comment by numero-744** [comment]
Ah it is not the whole VexRiscv stuff XD

**Comment by Readon** [comment]
> No no, it is fairly simple. It can be closed, as already merged : https://github.com/SpinalHDL/SpinalHDL/blob/dac69e9041b2c5ccabdd5bff79d49e20a2fcf093/lib/src/main/scala/spinal/lib/logic/Symplify.scala

Ahh, Symplify is a generic name. Might be hard to find, but at least there is an issue here.:)
