### ISSUE TITLE
AxiLite4SlaveFactory.onReadPrimitive does nothing when haltSensitive=false

### ISSUE THREAD

**Issue by kaofishy** [SpinalHDL/SpinalHDL#213]
When using `AxiLite4SlaveFactory.onReadPrimitive` with `haltSensitive` set to false, the associated anonymous function is never called.

I compared `AxiLite4SlaveFactory` with other `BusSlaveFactory` implementations and it looks like the difference is in the `build` method, `AxiLite4SlaveFactory` calls `doMappedReadElements` with `askRead = writeJoinEvent.valid` for some reason.

Edited to add the relevant section in AxiLite4SlaveFactory: https://github.com/SpinalHDL/SpinalHDL/blob/8109f9ef9d9f17f9f264477fb29f991f4f641c96/lib/src/main/scala/spinal/lib/bus/amba4/axilite/AxiLite4SlaveFactory.scala#L53-L65

**Comment by kaofishy** [comment]
Incidentally, as a side effect this means `multiCycleRead` doesn't do anything in `AxiLite4SlaveFactory` since it relies on `onReadPrimitive` to halt the bus. See: https://github.com/SpinalHDL/SpinalHDL/blob/8109f9ef9d9f17f9f264477fb29f991f4f641c96/lib/src/main/scala/spinal/lib/bus/misc/BusSlaveFactory.scala#L537-L549

**Comment by Dolu1990** [comment]
Ahhhh askRead = writeJoinEvent.valid,   nice catch XD

I just submited a fix 0a8a9bfed86a144c4696f72765380294d1a5d277
Let's me know if you still have issues :)

**Comment by kaofishy** [comment]
Yes this works perfectly now. Thanks!

**Comment by Dolu1990** [comment]
It is now released in 1.3.5 :)
