### ISSUE TITLE
Setting verbosity level of SpinalHDL compiler

### ISSUE THREAD

**Issue by chickenjohn** [SpinalHDL/SpinalHDL#215]
Currently the SpinalHDL compiler outputs a lot "[info]" such as "[Progress] emit ...(module name)" and "[Warning] memReadSync with dontCare...". Wouldn't it be great if users can set the verbosity level of these information? For example, printing out the [Warning] only.

**Comment by Dolu1990** [comment]
Hmm, probably all of those message, excepted the warning, should not be displayed by default.
Currently, there is now way to reduce it.

I will improve it for the next release :)

**Comment by Dolu1990** [comment]
I cleaned already a bit as i need to do a release now.
Should add a veribosity level to allow bringing things back

**Comment by Dolu1990** [comment]
Verbosity was quite reduced in 1.3.8
