### ISSUE TITLE
Conditional state transition for statemachine

### ISSUE THREAD

**Issue by rpls** [SpinalHDL/SpinalHDL#219]
Is it possible to only transition a StateMachine when a condition is met? Obviously, this is possible with `when()` inside the states, but what if the condition is always the same? Let's say we have the following code:

```scala
val cond : Bool = /* ... */

val fsm = new StateMachine {
  val STATE1 = new State
  val STATE2 = new State
  /* ... */
  STATE1.whenIsActive {
    when(cond) {
      goto(STATE2)
     }
  }
  STATE2.whenIsActive {
    when(cond) {
      goto(STATEN)
     }
  }
}
```

Instead maybe something like this:

```scala
val cond : Bool = /* ... */

val fsm = new StateMachine {
  val STATE1 = new State
  val STATE2 = new State
  /* ... */
  /* Imaginary API */
  onlyTransitionWhen(cond)
  STATE1.whenIsActive {
    goto(STATE2)
  }
  STATE2.whenIsActive {
    goto(STATEN)
  }
}
```

I.e. only latch `stateNext` into `stateReg` when `cond` is `True`. Or would this be bad-practice?

**Comment by rpls** [comment]
I guess without a new API, the following would achieve this?

```scala
val cond : Bool = /* ... */

val fsm = new StateMachine {
  val STATE1 = new State
  val STATE2 = new State
  /* ... */
  val _stateNext = enumDefinition()
  always {
    when(cond) {
      stateNext := _stateNext
    }
  }
  STATE1.whenIsActive {
    _stateNext := enumOf(STATE2)
  }
  STATE2.whenIsActive {
    _stateNext := enumOf(STATEN)
  }
}
```

**Comment by Dolu1990** [comment]
hmm you want something behaving like a clock enable ?
Maybe using the clockEnable of ClockDomain would be good for your usecase ?

Currently, there is nothing in the FSM API itself.

**Comment by rpls** [comment]
Yes, clockEnable might be an Idea. For reference, I‘m trying to get more
into SpinalHDL (and HDL in general) by building a CAN FD transceiver
component. So I‘m currently working on the FSM which sends and/or parses
the CAN frame, and the FSM pretty much only needs to react when a bit is
sampled, which may happen in time intervals anywhere from a few clocks to
hundreds. So I want to avoid something along the lines of
`when(input.valid)` in every state, both to clean up the code and to avoid
all the additional logic (unless I misunderstand something about what kind
of logic will be generated by this?).

So how would I go about this? Place the FSM in a ClockDomain with the same
Clock but with the clockEnable set when a bit is sampled? Might just be a
problem because the FSM will push some bits into a shift-register to send
out.

**Comment by Dolu1990** [comment]
hmm
I understand that need. So maybe it would be great to add that to the FSM API. a global state transition enable. It would not be hard to do.

Do you wanna try to add this in the FSM API ?

**Comment by rpls** [comment]
Yeah, I’ll fork the repo and send a PR.

**Comment by Dolu1990** [comment]
Cool :D
