### ISSUE TITLE
ModuleNotFoundError: No module named 'Queue'

### ISSUE THREAD

**Issue by Divyanirankari** [SpinalHDL/SpinalHDL#242]
mod = __import__(name)
                                                                                                                       File AxiLite4SlaveFactoryTester.py", line 2, in <module>
                                                                                                                         from Queue import Queue
                                                                                                                     ModuleNotFoundError: No module named 'Queue'

**Comment by Dolu1990** [comment]
Sorry, i'm not sure to understand the nature of the issue ?
