### ISSUE TITLE
Enhancement:  B(value: Array[Byte][, x bits])

### ISSUE THREAD

**Issue by bellaz89** [SpinalHDL/SpinalHDL#245]
I don't know if I am missing something, but I found it hard to convert an arbitrary long word to Bits.
For this, I propose to add the following method  
```
B(value: Array[Byte][, x bits]): Byte
```
that produces a Bits literal with the data contained in value
if x < value.length * 8 then value is truncated. If x > value.length * 8 then value is padded with zeros. if x is not passed or x == x.length * 8, the final length is value.length * 8

This addition would be very useful IMHO when converting data read from a binary file or other binary sources to  SpinalHDL literals (for example to initialize a Mem..).

**Comment by bellaz89** [comment]
@Dolu1990

**Comment by Dolu1990** [comment]
Hmmm what's about Scala BigInt ?
You can assign them to signal in sim and rtl.

**Comment by bellaz89** [comment]
Yes.   This fits. Maybe then a doc reference to this has to be added (there is no reference to this in https://spinalhdl.github.io/SpinalDoc-RTD/SpinalHDL/Data%20types/bits.html) 

Thanks

**Comment by Dolu1990** [comment]
Hoo right, it only refer to Int

**Comment by bellaz89** [comment]
Also, is  B(value: BigInt) going to work with negative BigInts? As far as I remember last time I checked B(value: Int) didn't work with negative Ints. This could be a limitation for bit streams that starts with '1'

**Comment by Dolu1990** [comment]
That's done on purpose that negative value only work with SInt

**Comment by bellaz89** [comment]
Ahh ok, now I got it.. the right way to do it should be the following:

```
 B(BigInt(java.math.BigInteger(1, byteArray))) 
```
