### ISSUE TITLE
Template project with Gradle

### ISSUE THREAD

**Issue by piegamesde** [SpinalHDL/SpinalHDL#246]
Using SpinalHDL, I've come to learn that SBT is a strictly inferior build tool compared to Gradle (change my mind). So I took the Spinal base project and migrated it to use Gradle instead:

https://github.com/piegamesde/SpinalTemplateGradle

Would you accept integrating this into the SpinalHDL project account? I'd also update the README here on how to use it.

**Comment by Dolu1990** [comment]
Hi,

Sure, there is https://github.com/SpinalHDL/SpinalTemplateGradle :D thanks !

**Comment by piegamesde** [comment]
You just forked mine? :D I rather suggest to transfer ownership, if this is possible.

**Comment by Dolu1990** [comment]
Hooo, hmmm, i don't know if there is a way to transfer ownership in github. Personnaly, i'm fine with the fork, you did the job after all :)

**Comment by piegamesde** [comment]
Did the trick with deleting mine. (<https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/what-happens-to-forks-when-a-repository-is-deleted-or-changes-visibility>)

**Comment by Dolu1990** [comment]
RIP
