### ISSUE TITLE
Disable sbt interactive features in Travis

### ISSUE THREAD

**Issue by piegamesde** [SpinalHDL/SpinalHDL#252]
Currently, the output of the Travis CI when failing is very bloated. There are many empty lines and progress information that dilute the actually interesting stuff. I suspect this is because of "interactive" features that work well in user terminals, but not when the output is written to a file.

I don't know much about sbt, I couldn't find a name for this "feature" or how to disable it.

Example:

```
  | => core / Compile / unmanagedSources / inputFileStamps 0s
[error] Failed tests:
[5 empty lines]
  | => core / Compile / unmanagedSources / inputFileStamps 0s
[error] 	spinal.tester.scalatest.MandelbrotTesterCocotbBoot
[5 empty lines]
  | => core / Compile / unmanagedSources / inputFileStamps 0s
[5 empty lines]
[error] (tester / Test / test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 944 s (15:44), completed Jan 11, 2020 9:32:29 PM
```

**Comment by Dolu1990** [comment]
To be honnest i don't remember exactly about it.
@1138-4EB Does it tell you something ?

**Comment by Dolu1990** [comment]
Ahh maybe that's also due to the SBT update ? it behave quite differently with the console

**Comment by piegamesde** [comment]
Try running the CI builds with `sbt --supershell=false`. I've tried `sbt --batch` as well and it seems to work, so maybe `--batch` implies `--supershell=false`?
