### ISSUE TITLE
Travis doesn't push container to dockerhub

### ISSUE THREAD

**Issue by wifasoi** [SpinalHDL/SpinalHDL#269]
I noticed that travis does exit with an error in the publish stage.
https://travis-ci.org/SpinalHDL/SpinalHDL/jobs/634856950?utm_medium=notification&utm_source=github_status

It seams a problem with "docker-credential-helpers". I'll fix it later(this just a reminder for me).

**Comment by wifasoi** [comment]
Found a possible issue here:
https://github.com/SpinalHDL/SpinalHDL/blob/cc22f06e064f41c95fa1e009622ee1e144085040/travis.sh#L82
(need the z flag i think)

**Comment by Dolu1990** [comment]
I absolutly have no idea about all of this work, sorry XD

**Comment by numero-744** [comment]
Travis is outdated
