### ISSUE TITLE
Specifying Seed for the Simulation

### ISSUE THREAD

**Issue by distributed** [SpinalHDL/SpinalHDL#281]
I have a simualtion that failed once and printed this:

```
[info] [Progress] Start JpegWriter jpegwriter simulation with seed 8223987900762028738, wave in /home/joe/FPGA/proj/hdl/cisc/./simWorkspace/JpegWriter/jpegwriter.vcd
```

Now I am trying to rerun the same simulation, like so:

```
compiledSim.doSimUntilVoid("jpegwriter", seed=8223987900762028738L) { dut =>
```

However now the simulations runs with a different seed:

```
[info] [Progress] Start JpegWriter jpegwriter simulation with seed 3313447782858668379, wave in /home/joe/FPGA/proj/hdl/cisc/./simWorkspace/JpegWriter/jpegwriter.vcd
```

However, a seed a given to `doSim` seems to result in always the same (different from the original) seed.

**Comment by Dolu1990** [comment]
Fixed in dev ^^
Thanks :)

**Comment by distributed** [comment]
Merci beaucoup! I will start using it tomorrow :)

**Comment by distributed** [comment]
Works like a charm.
