### ISSUE TITLE
Couldn't find out the `w.id` signal in Axi4

### ISSUE THREAD

**Issue by wswslzp** [SpinalHDL/SpinalHDL#346]
I couldn't find out the `id` signal in Axi4W channel while the Axi4AW channel have. It's a big problem that write channel does not have an id tag.

**Comment by Dolu1990** [comment]
That's the difference between AXI4 and AXI3 isn't it ?
AXI4 has no wid if i remember well

**Comment by wswslzp** [comment]
yes, u r right
