### ISSUE TITLE
BlackBox Generic does not accept Spinal types as members

### ISSUE THREAD

**Issue by kaofishy** [SpinalHDL/SpinalHDL#355]
I'm using SpinalHDL 1.4.2 and when I instantiate a `BlackBox` with a `Generic`, the `Generic` instance does not accept Spinal types (eg `Bool`) as members; the SpinalHDL runtime throws a `NoSuchElementException`. `addGeneric()` works as expected, however.

See the minimal test case below to reproduce the issue:

```scala
import spinal.core._

class TestBlackBox extends BlackBox {
  val generic = new Generic {
    val parameter1 = True
  }
  // this works
  // addGeneric("parameter", True)
}
class TestInst extends Component {
  val testbb = new TestBlackBox
}

object TestBlackBox {
  def main(args: Array[String]): Unit = {
    SpinalVerilog(new TestInst)
  }
}
```

**Comment by Dolu1990** [comment]
Thanks :)
Should be fine now in dev
