### ISSUE TITLE
is there any optional to remove 'empty case' in generated RTL

### ISSUE THREAD

**Issue by curliph** [SpinalHDL/SpinalHDL#361]
cause we have a default case, so  can not just remove all empty case?

**Comment by Dolu1990** [comment]
Which version of SpinalHDL are you using ?

Currently it already seems to remove empty case in dev branch (and i had kind of a remember that i have done that change)

**Comment by curliph** [comment]
sorry, You right!  I use spinalhdl 1.4.0...
Now change to 1.4.2,  good job!

**Comment by Dolu1990** [comment]
No worries :)
