### ISSUE TITLE
Axi4ReadyOnlyCC really should be Axi4ReadOnlyCC, "Read" instead of "Ready"

### ISSUE THREAD

**Issue by sammhho** [SpinalHDL/SpinalHDL#380]
That's probably a typo in the case class name (am I the only one using this class? lol ):
https://github.com/SpinalHDL/SpinalHDL/blob/70f4a073bf94d3f4687487946cdc70c35f7d65a2/lib/src/main/scala/spinal/lib/bus/amba4/axi/Axi4CC.scala#L6

**Comment by Dolu1990** [comment]
Thanks ^^
