### ISSUE TITLE
Radix for switch statement

### ISSUE THREAD

**Issue by chonwhite** [SpinalHDL/SpinalHDL#384]
There is no way to set radix for the switch statement, but sometimes binary representation may make more sense than octal. So it would be nice to be able to set radix for the switch statement;

**Comment by numero-744** [comment]
You mean in generated code?

**Comment by chonwhite** [comment]
yup

**Comment by numero-744** [comment]
I don't think so, and it seems hard to implement (have to transmit the information down to the different code generators). But I don't think it is important except for debugging SpinalHDL itself, which you don't need to (I hope :smile:)
