### ISSUE TITLE
Why do the util.CountOne using lut grouped by 3?

### ISSUE THREAD

**Issue by JimmyJuan** [SpinalHDL/SpinalHDL#407]
https://github.com/SpinalHDL/SpinalHDL/blob/70436f83e9543033d62e6d00ca87b79a80c2d5c4/lib/src/main/scala/spinal/lib/Utils.scala#L167-L177

I don't understand why the inputs are grouped by 3, and then went through a lut.
As far as I know, different part of FPGA has different architecture, the size of LUT in CLB(slice) is different. I don't think it's a good idea to write it that way.

**Comment by Dolu1990** [comment]
Hi,

Basicaly, i set it to 3 there to already have the functionality working.

I agree this is not greate, this parameter could be either a arguement of the function, either it could be loaded from the SpinalConfig used to generate the hardware.

**Comment by Dolu1990** [comment]
Finaly implemented XD

Thanks for the issue :)

**Comment by Dolu1990** [comment]
So before your SpinalVerilog / SpinalVhdl, you can do   LutInputs.set(6)   for instance, or LutInputs(6).on{ yourCode here }
