### ISSUE TITLE
Bit extraction from Vec

### ISSUE THREAD

**Issue by huang-jl** [SpinalHDL/SpinalHDL#425]
Hi, I meet a problem with bit extraction from signal inside a `Vec`

```scala
val data = Vec(Bits(32 bits), 8)
val addr = UInt(3 bits)
//...
data(addr)(0, 8 bits) := U(0, 8 bits)
```

The error after running is:
```
WIDTH MISMATCH on (toplevel/data_0 :  Bits[32 bits]) := (B"00000000" 8 bits) at 
...
WIDTH MISMATCH on (toplevel/data_7 :  Bits[32 bits]) := (B"00000000" 8 bits) at 
```

How can I assign only some bits of one signal inside `Vec` (which is `data` in the example)?

**Comment by huang-jl** [comment]
@Dolu1990 Looking forward to your help.

**Comment by Ncerzzk** [comment]
I also met the problem.  Do you solve it? @huang-jl 

@Dolu1990

**Comment by Dolu1990** [comment]
Ahh damned, i missed that issue.
I will give some checks, i think i may have fix something related to that. but i have to check.

**Comment by Dolu1990** [comment]
Else there is still the work around to manualy handle it : 
```scala
for(i <- 0 to 8) when(addr === i) { data(i)(0, 8 bits := U(0, 8 bits) }
````

**Comment by Dolu1990** [comment]
I just tested, it was fixed. 1.6.1 should work.
