### ISSUE TITLE
SpinalGradleTemplate maintenance

### ISSUE THREAD

**Issue by piegamesde** [SpinalHDL/SpinalHDL#443]
I've had a look at https://github.com/SpinalHDL/SpinalTemplateGradle again and it got seriously outdated (bit rot, yay). Of course, I could fork it and make pull requests, but since I originally wrote it could you please simply give me commit access? Also please enable issues on it, so that users can get support if they have trouble using it.

@Dolu1990

**Comment by Dolu1990** [comment]
> (bit rot, yay)

Rawrrrr <3

> Of course, I could fork it and make pull requests, but since I originally wrote it could you please simply give me commit access? Also please enable issues on it, so that users can get support if they have trouble using it. 

All done.

Thanks :)
