### ISSUE TITLE
Should `waitEdge()` really wait for the next rising edge?

### ISSUE THREAD

**Issue by jonnykl** [SpinalHDL/SpinalHDL#466]
`waitEdge()` waits for the next rising edge, but `waitEdge(n)` waits for any next edge. Is this really the wanted behaviour?

https://github.com/SpinalHDL/SpinalHDL/blob/a61f1bf3976c0a9719fc148273cad3a75c86eec0/core/src/main/scala/spinal/core/sim/package.scala#L514

**Comment by Dolu1990** [comment]
Right, copy past mistake ^^
Thanks :)
