### ISSUE TITLE
why use hitDoWrite in RS register?

### ISSUE THREAD

**Issue by aiit-linry** [SpinalHDL/SpinalHDL#473]
https://github.com/SpinalHDL/SpinalHDL/blob/e60e9077adca90fba453b3831183caf67f7dd6c7/lib/src/main/scala/spinal/lib/bus/regif/RegInst.scala#L169

**Comment by Dolu1990** [comment]
@jijingg  0xEE ^^

**Comment by jijingg** [comment]
@aiit-linry sorry , that' a bug  fix in #478

**Comment by Dolu1990** [comment]
merged <3
