### ISSUE TITLE
Repeating "_1" suffixes of the name of verilator working directory

### ISSUE THREAD

**Issue by wswslzp** [SpinalHDL/SpinalHDL#486]
When using the `spinal sim` to do the regression tests on the same dut with verilator backend,  spinal will rename the simulation workspace by adding the suffix `_1` after the previous one, in order to avoid the naming conflict. However, the name will soon be lengthy if there are many test cases to run, shown as below
![image](https://user-images.githubusercontent.com/30322341/127870153-fc6b483b-b657-4db8-8d47-cc2372b286aa.png)
Maybe replacing the repeating `_1` with `_<incremental_number>`, e.g. `_1_1` with `_2`, is more reasonable and expected.

**Comment by Dolu1990** [comment]
Ahh, i was able to reproduce the case when reusing the same SimConfig multiple times. I pushed a fix. Can you give a try and let me know if things are also fixed for you ?

**Comment by wswslzp** [comment]
Thanks very much for your works, the issue is fixed!
