### ISSUE TITLE
Payload is not assigned when using StreamJoin.vec

### ISSUE THREAD

**Issue by teilraum** [SpinalHDL/SpinalHDL#501]
https://github.com/SpinalHDL/SpinalHDL/blob/2183600a8a77205997744ec1261eb1584c17f657/lib/src/main/scala/spinal/lib/Stream.scala#L862-L867

If we assign the payload manually and only use StreamJoin.apply (ignoring the payload), it works. 

maybe add
```combined.payload := Vec(sources.map(_.payload))```
to fix the problem...

**Comment by Dolu1990** [comment]
Hooo right, can you open a pull request ?

Thanks :D

**Comment by teilraum** [comment]
done
