### ISSUE TITLE
Scastie: how to redirect stdout of spinal.sim

### ISSUE THREAD

**Issue by 0xcdef** [SpinalHDL/SpinalHDL#503]
So it's really not a problem of SpinalHDL, but I think you can give me some help!

I try to run spinal with Scastie, (https://scastie.scala-lang.org)
I set  "fork := true"  to run spinal simulation,
As I can see,  it build and run without any problem,  but I can not see any print string...
So, is there any simple way to redirect Spinal.sim to our main console?

Thanks and best regards,

**Comment by numero-744** [comment]
Have you tried this? https://github.com/SpinalHDL/Spinal-bootcamp
