### ISSUE TITLE
Vivado benchmark not adding input/output delay

### ISSUE THREAD

**Issue by jiegec** [SpinalHDL/SpinalHDL#532]
Currently, the VivadoFlow class does not generate constraints for input/output delay. If a fully combinatorial module is benched, the reported timing is wrong because there are no delays specified for input and output.

**Comment by Dolu1990** [comment]
I'm not sure what is the best solution between adding timings constraints on the io, which will stretch out the design, and so, not be greate for the timings, or using some  toplevel transformations as :
https://github.com/SpinalHDL/SpinalHDL/blob/3b87c898cb94dc08456b4fe2b1e8b145e6c86f63/lib/src/main/scala/spinal/lib/eda/bench/Bench.scala#L36

Which add 3 flip flops on each in / out pin.

**Comment by jiegec** [comment]
Nice catch.
