### ISSUE TITLE
DecoderSimplePlugin assertIllegalInstruction false positive

### ISSUE THREAD

**Issue by piegamesde** [SpinalHDL/SpinalHDL#544]
I tried to set the `assertIllegalInstruction` option of `DecoderSimplePlugin` and my simulation instantly failed although it shouldn't. Looking at the wave trace, this already happens in the first cycle after the reset goes down.  Looking some more, the problem may be related to the fact the the `decodeExceptionPort.valid` signal is kept high for one cycle after a reset, which I think triggers the false positive. Note that `catchIllegalInstruction` appears to be working just fine somehow.

**Comment by wswslzp** [comment]
Is this a vexriscv issue?

**Comment by piegamesde** [comment]
Oops. Yes it is, please move to the VexRiscv repository (I think GitHub has this feature)

**Comment by piegamesde** [comment]
Moved to https://github.com/SpinalHDL/VexRiscv/issues/225
