### ISSUE TITLE
Axi4 SlaveFactory handshake problem

### ISSUE THREAD

**Issue by raochl** [SpinalHDL/SpinalHDL#549]
Hi, there. I create an AXI4 slave with `Axi4SlaveFactory`. 
1. when I simulated the function of my write behavior, I found that the slave may not assert the `aw_ready` and `w_ready` signal before I set the `b_ready` signal.  As follows:
![image](https://user-images.githubusercontent.com/38033760/146393832-c10f8dff-fb9d-435a-aaca-f7b25c675b34.png)

It seems not very reasonable. Sometimes, a master may send write address first. After the write address channel handshakes, the master can then write the data into the write data channel. After the write data transmitted is finished, master then can set the `b_ready` to receive the write response from the slave. 
Here, the `b_valid` should not rely on `b_ready`, the `w_ready` and `aw_ready` may not correlate with the `b_ready` signal. 

2. The `writeMultiWord` function cannot write a burst transmit with multiple data. The data are all written into the first address. Unless I initiate multiple burst transmit each with one length of data. I don't know if I use it correctly.

**Comment by Dolu1990** [comment]
2) the axi4 factory is made to handle peripheral type accesses, not burst. It maybe possible to implement it, but it wasn't realy a need to far.

1) I'm not sure of the diagnostic, i mean, what's about the w_valid in your simulation ? why is it only showing so late at the same cycle ?

I mean, from : 
https://developer.arm.com/documentation/ihi0022/e/AMBA-AXI3-and-AXI4-Protocol-Specification/Single-Interface-Requirements/Relationships-between-the-channels/Dependencies-between-channel-handshake-signals?lang=en

"the slave can wait for AWVALID or WVALID, or both before asserting AWREADY"

**Comment by raochl** [comment]
Yes, the AWREADY can wait for AWVALID and WVALID before asserted. But at the simulation of my case, I just delay one cycle and then set the WVALID. The AWREADY and WREADY didn't assert until 5 cycles later when I set the BREADY.

**Comment by Dolu1990** [comment]
Hoo, looking at the implement, i can't find any buffer between the aw/w join to the b channel, i will add it, this should fix the issue ^^

**Comment by Dolu1990** [comment]
I pushed the fix for point 1

**Comment by raochl** [comment]
works very well. Thanks
