### ISSUE TITLE
A Register in Bool.fall() is not Initialized

### ISSUE THREAD

**Issue by ZimingYuan** [SpinalHDL/SpinalHDL#551]
In `SpinalHDL/core/src/main/scala/spinal/core/Bool.scala`, line 137:
```
 def fall(): Bool = ! this && RegNext(this)
```
The register is never initialized in the code. Sometimes it will be mistakenly initialized to True and this will cause wrong result.
I think this overload of the function is misleading. It's better to delete it or initialize the register to the default value False.

**Comment by wswslzp** [comment]
![image](https://user-images.githubusercontent.com/30322341/146492260-817ad5c9-a0bc-441e-aa7c-1914bf169e81.png)
There is a `fall()` version with an initialization value.

**Comment by ZimingYuan** [comment]
> ![image](https://user-images.githubusercontent.com/30322341/146492260-817ad5c9-a0bc-441e-aa7c-1914bf169e81.png) There is a `fall()` version with an initialization value, just at line 135.

I know. I mean someone (careless people like me) may mistakenly use the version in line 137. Since it's misleading, it would be better to just delete or modify it.

**Comment by Dolu1990** [comment]
Hmm, maybe renaming it into fallWithoutInit, but then things become soooo verbose.

**Comment by numero-744** [comment]
I agree I think we can do the parallel with `RegNext` which would become `RegNextWithoutInit`.

This kind of mistake can be detected, I think. How? Is there a `Phase` do detect registers without `init`? If so, how to use it? I cannot find this on RTD.

But this is going a little bit off-topic for an old issue so I close it ^^' (but I'm still curious about the answer).

**Comment by Dolu1990** [comment]
>  Is there a Phase do detect registers without init

There is a phase which check if registers aren't driven (no init / no assignement).
Also there is a phase which translate register with only init into literals.

> This kind of mistake can be detected,

User side mistake, but legal hardware, so not realy catchable ?

**Comment by numero-744** [comment]
I mean detect it as an option. Maybe with #916 it can be easier, using `allReg` and check for each reg if it has an `init`?

**Comment by Dolu1990** [comment]
Sure #916 can help looking at it.
But overall, i would say having all registers with an init value is a bad practice, so not sure it is so helpfull.
We could generate a list of all the registers with init for the user to look at, but it seems to me that there will just be too much to look at very fast (ex vivado warning ocean ^^)

**Comment by Dolu1990** [comment]
On FPGA : 
- Consume the clr thing, which could have been used for other usages. So use more LUT and decrease FMAX. It can realy be a big deal, as the FMax impact isn't necessarly small. (from my experience) (also, more lut used => less compact design => more time to travel between LUT)

On ASIC : 
- I'm not an expert at all, but likely having the reset increase the area and add some delay. Also, increasing the area by itself can reduce the FMax of the design, as it mean less compact logic => bigger distance to travel. But i have no data to back any of those claims ^^
