### ISSUE TITLE
Please, open a issue to discuss, before implementing changes

### ISSUE THREAD

**Issue by Dolu1990** [SpinalHDL/SpinalHDL#571]

**Comment by numero-744** [comment]
https://github.com/SpinalHDL/SpinalHDL/issues/892 is not pinned but it seems it should.

Could the title of this (#571) issue be added on top of https://github.com/SpinalHDL/SpinalHDL/issues/619 and the issue be deleted?

**Comment by Dolu1990** [comment]
> https://github.com/SpinalHDL/SpinalHDL/issues/892 is not pinned but it seems it should.

Yes right XD i was sad when i have seen that there is a limitation for the number of pinned issues to 3 XD

> Could the title of this (https://github.com/SpinalHDL/SpinalHDL/issues/571) issue be added on top of https://github.com/SpinalHDL/SpinalHDL/issues/619 and the issue be deleted?

Hmm i think you are right. It can be done.
