### ISSUE TITLE
UartCtrlIo and the xUartCtrl implementations missing RTS and CTS generation

### ISSUE THREAD

**Issue by FredrikAleksander** [SpinalHDL/SpinalHDL#594]
The UartCtrlIo class does not take the provided ctsGen and rtsGen configuration options into consideration when defining
the Uart bus. The same applies for Apb3UartCtrl, AvalonMMUartCtrl, BmbUartCtrl and WishboneUartCtrl. I have fixed these issues locally, and I can make a pull request with my changes if that is desired (https://github.com/FredrikAleksander/SpinalHDL/commit/b9371dc6d886707a6c0ae5354493d136f7ac95b0)

**Comment by Dolu1990** [comment]
Thanks !
I merged your branch :)
