### ISSUE TITLE
add io signal by component.current.getAllIO

### ISSUE THREAD

**Issue by openRV** [SpinalHDL/SpinalHDL#616]
I tried to add signal by `component.current.getAllIO : mutable.Set[BaseType]`, with a template variable inferring BaseType like this:
``` scala
    def fn [T <: BaseType] (type:T) {
        val ios = Component.current.getAllIO
        ios += in(type)       // signal 1
        ios += out(type)    // signal 2
    }
```
and by `println(ios)`
I just found that signal 1 and signal 2 in generated ios are the same.

while changed type to such as UInt(32 bits), that just work fine, and correctly added 2 different in and out signal.
I would like to know whether it's a bug or I have some other way to do this.

I would like to add io signals from mutable Vector, is it possible?

**Comment by Dolu1990** [comment]
Hi

```scala
    def fn [T <: BaseType] (type:HardType[T]) {
       in(type())       // signal 1
       out(type())    // signal 2
    }
    ```

should be good normaly

in() and out() both are modifiers to the parameter, they do not create anything.
Also they add the given arguements to the Component.current list already :)

**Comment by openRV** [comment]
of course it can， but I'd like to add customized signals, which can't infer num, type or bitwidth in advance.
such as an abstract class of all pipeline regs (or maybe can I use trait to do that?)

**Comment by Dolu1990** [comment]
Do you have some example of the API usage ? I'm not exactly sure of the goal you are aiming for.

**Comment by openRV** [comment]
just research purpose, there is an example following
```scala

    // decalration could be:
    val PipelineReg = Pipeline( Bits(2 bits) , Int(32 bits) )
    // like a bundle of RegNext of different type

    // maybe I can get io values like this:
    val a = Bits(2 bits)
    val b = Bits(2 bits)
    // for example, just a pulse length delay
    a := PipelineReg.io.first( in )
    b := PipelineReg.io.second( out )
    // it performance like b := RegNext(a)
```

I have no idea whether it's possible

**Comment by Dolu1990** [comment]
Ahhh, so you want to do some auto pipelining ?

For instance, NaxRiscv has a pipelining API : 
https://spinalhdl.github.io/NaxRiscv-Rtd/main/NaxRiscv/abstraction/index.html#pipeline

About your example, what is the "in" and "out" in the last part ? 
PipelineReg.io.first( in )
PipelineReg.io.second( out )

 ?

**Comment by openRV** [comment]
yes, that's just what I want.  Thank you so much.

I'm not quite sure about that, but maybe a symbol that can help me get the input or output signal of the auto generated Pipeline module? If it's possible to do this in this way or something else?

**Comment by Dolu1990** [comment]
So, one thing, is that when i was doing the pipeline API for VexRiscv and Nax, i avoided using Component to encapsulate the pipeline.

Instead i was using a Area, that way it provide a namespace while preserving full access to the signal (component can be cumbersome)

**Comment by openRV** [comment]
Ok, I've learned that. But if there is any document of such inner component like area in SpinalHDL ?

**Comment by Dolu1990** [comment]
Sure : 
https://spinalhdl.github.io/SpinalDoc-RTD/master/SpinalHDL/Structuring/area.html

**Comment by openRV** [comment]
I see , thank you so much
