### ISSUE TITLE
Is there a method for multiple module auto-connect?

### ISSUE THREAD

**Issue by dxsm** [SpinalHDL/SpinalHDL#626]
![image](https://user-images.githubusercontent.com/42776212/155951707-f918404b-c3ee-4ff1-b94f-6fd832645d36.png)

As above, is there a method as
```scala
autoConnect(A,B,C,D, io, function() {
A.sig1 <> B.sig1_aa
})
```
make module A/B/C/D and top.io autoConnect with same port name instead of use `<>` one by one, and report the unconnect port which can not found the same port. Then user can connect in a function in hand.

**Comment by Dolu1990** [comment]
Hi, 

currently there is nothing like this.
All the data are there to make it possible, so it is mostly about analysing the data.

I guess the feature could is composed of two things : 

- How to extract a pool of interface
- How to connect them

So, do we want to have a pool of interface or a pool of basetype. Probably a pool of basetypes would be less problematic
