### ISSUE TITLE
Axi4SpecRenamer can not work with Axi4ReadOnly/WriteOnly.

### ISSUE THREAD

**Issue by linuxbest** [SpinalHDL/SpinalHDL#63]
val cmd  = master(Axi4ReadOnly(cmdg.getAxi4Config))
....
Axi4SpecRenamer(io.cmd)

then I got error message.
 
[error] /home/steve/src/ssd/arcdome/src/main/scala/dma.scala:64: type mismatch;
[error]  found   : spinal.lib.bus.amba4.axi.Axi4ReadOnly
[error]  required: spinal.lib.bus.amba4.axi.Axi4
[error]   Axi4SpecRenamer(io.cmd)

Thanks.

**Comment by Dolu1990** [comment]
Hi,

I submited a fix. (f8130ec95dd8b4d739cccabd2caaea2c74f92aac)
Because currently it's not released on sonatype, to use this fix you can get the sources of SpinalHDL, and do a sbt publish-local   and force your sbt scripte to use the 0.10.13.

Let's me know if you get others issue :)
