### ISSUE TITLE
How to update spinal to the latest version for existing projects

### ISSUE THREAD

**Issue by Aaronwangyilun** [SpinalHDL/SpinalHDL#654]
I am a beginner, I would like to ask how to update spinal to the latest version for existing projects.

**Comment by tanhongze** [comment]
If you starts your project from `SpinalTemplateSbt`, find `build.sbt`
The version of spinal is specified by a variable in that file
e.g. ```val spinalVersion = "1.6.4"```
To update spinal to the latest version, simply change it to the lastest

**Comment by Aaronwangyilun** [comment]
Thanks a lot!~now I am using IDEA, can I only regenerate the new project with the new version of build.sbt and include the code in it?

> If you starts your project from `SpinalTemplateSbt`, find `build.sbt` The version of spinal is specified by a variable in that file e.g. `val spinalVersion = "1.6.4"` To update spinal to the latest version, simply change it to the lastest

**Comment by Aaronwangyilun** [comment]
> If you starts your project from `SpinalTemplateSbt`, find `build.sbt` The version of spinal is specified by a variable in that file e.g. `val spinalVersion = "1.6.4"` To update spinal to the latest version, simply change it to the lastest

Thank you very much! I modified the build.sbt file and updated it, and I succeeded

**Comment by Dolu1990** [comment]
> Thanks a lot!~now I am using IDEA, can I only regenerate the new project with the new version of build.sbt and include the code in it?

So normaly, you only need to do a refresh: 
view/tool windows/sbt and then =>
![image](https://user-images.githubusercontent.com/4832082/160102320-2f604e7f-4107-46f7-91fd-553e9200517c.png)
