### ISSUE TITLE
Fix `AxiMemorySim`?

### ISSUE THREAD

**Issue by tanhongze** [SpinalHDL/SpinalHDL#659]
I found that `spinal.lib.bus.amba4.axi.sim.AxiMemorySim` does not obey AXI4 specification
There are a few sub-issues
1. Cannot correctly reply `rid` (not driven now)
2. read/write transactions is not correct when address is not aligned
e.g. 
We have `32'h3210` at address 0 and `32'h7654` at address 4.
The bus should reply `32'h3210` (generally `32'h--1-`) when address 1 is required and `arsize` is set to 0, instead of `32'h4321`

**Comment by tanhongze** [comment]
Could I fix `AxiMemorySim`? Is there any requirement for PR?

**Comment by c-thaler** [comment]
Your fix will be highly appreciated :D

**Comment by Dolu1990** [comment]
> Is there any requirement for PR?

I would say, the requirement is to fix more than it break ^^

And to not break backward compatibility.
