### ISSUE TITLE
How about add a regroup function for BitVector?

### ISSUE THREAD

**Issue by Readon** [SpinalHDL/SpinalHDL#677]
sometimes, a regroup on bits is required, such as D[31:0] ==> {D[7:0], D[15:8], D[23:16], D[31:24]}.
how about add a regroup function for BitVector, so that the usage can be as below.
``` scala
     val a = Bits(32 bits)
     a.regroup(8 bits) { (i, total) =>
         total - 1 - i
     }
     // the implementation could be 
     def regroup(sliceWidth bits)(indexMap: (Int, Int) => Int) {
          val inVec = this.subdivideIn(sliceWidth)
          val outVec = cloneOf(inVec)
          for(i <- inVec.indexes) {
              outVec(indexMap(i)) := inVec(i)
          }
         val out = cloneOf(this)
         out.asBits := outVec.asBits   //this might require correction.
     }
```

**Comment by tanhongze** [comment]
`D[31:0] ==> {D[7:0], D[15:8], D[23:16], D[31:24]}` is already implemented as `EndiannessSwap`

**Comment by Readon** [comment]
> `D[31:0] ==> {D[7:0], D[15:8], D[23:16], D[31:24]}` is already implemented as `EndiannessSwap`

em, it's just an example, it could be more flexible.

**Comment by Dolu1990** [comment]
Hi,

hmmm maybe this could be implemened by adding / composing smaller primitives ?

a.subdivideIn(8 bits).shuffle(x => y).asBits ?

Having both subdibide and shuffle inside a single function seems a lot ?

**Comment by Readon** [comment]
> e inside a single function seem

yes, that would be better to keep things simple. 
Then there should be a shuffle method of Vec, which also leave the type problem to user when output type is not Bits.
