### ISSUE TITLE
How about adding a `getPath` method to `BaseType`?

### ISSUE THREAD

**Issue by wswslzp** [SpinalHDL/SpinalHDL#687]
As the `getPath` method of `Component`, sometimes it's useful to get the hierarchy of a signal/pin/port when writing EDA tool scripts.

**Comment by Dolu1990** [comment]
Added ^^
So, i think the best is to not have the toplevel/ at the begining, i added getRtlPath in both Data and Component class with that behaviour

**Comment by wswslzp** [comment]
Thanks!
