### ISSUE TITLE
all signal name _zz_ when use 1.7.0 in Linux

### ISSUE THREAD

**Issue by aiit-linry** [SpinalHDL/SpinalHDL#719]
Its OK in windows or use 1.6.4 in Linux, include centos 7.9 and ubuntu 18.04

**Comment by aiit-linry** [comment]
When using scala version > 2.13

**Comment by aiit-linry** [comment]
1.7.0+2.12.x = compile failed,
![image](https://user-images.githubusercontent.com/84612860/166906448-131bf69a-ee8f-43ea-9b33-78f6663745f8.png)

1.7.0+2.13.x = zz in names

1.7.0+2.11.x = everything OK , but i need Random.nextLong function in 2.13.x :(

hope fix this issue

**Comment by tanhongze** [comment]
I use Linux with Spinal 1.7.0 and scala 2.13.8 too.
However, everything seems OK in my environment. 
What's the different?

**Comment by Dolu1990** [comment]
I noticed that when i was updating project which were already compiled once with a older version, i had some issue.

Did you tried "sbt clean" ?

**Comment by aiit-linry** [comment]
> I use Linux with Spinal 1.7.0 and scala 2.13.8 too. However, everything seems OK in my environment. What's the different?

![image](https://user-images.githubusercontent.com/84612860/167749746-2efc4898-c1c9-461e-a4a8-5695daa0215a.png)
![image](https://user-images.githubusercontent.com/84612860/167749926-36b0bd90-fa09-4072-8367-dcdc496121dd.png)

Are there any errors in my configuration? I tried template and only modify scala version to 2.13.8.

**Comment by aiit-linry** [comment]
> I noticed that when i was updating project which were already compiled once with a older version, i had some issue.
> 
> Did you tried "sbt clean" ?

yeap, I tried "sbt clean", it seems doesnt work. :(

**Comment by aiit-linry** [comment]
But Its OK in my windows env, that is really confusing.

**Comment by Dolu1990** [comment]
I just tested on my side, Scala 2.13.8, all seems fine.

Which version of java / javac do you have ? (--version)

**Comment by aiit-linry** [comment]
> I just tested on my side, Scala 2.13.8, all seems fine.
> 
> Which version of java / javac do you have ? (--version)

javac 1.8.0_312 in my ubuntu and javac 1.8.0_262 in my centos

**Comment by numero-744** [comment]
Hi @aiit-linry,
Is the issue still here?

Else have you tried `sbt clean` as Dolu mentioned?

**Comment by aiit-linry** [comment]
> Hi @aiit-linry, Is the issue still here?
> 
> Else have you tried `sbt clean` as Dolu mentioned?

yes, it is still in 1.7.0, I have tried 'sbt clean' but it doesnt work. But when I update spinal version to 1.7.2, all is well in my ubuntu and my centos. @numero-744 
should I close this issue under this circumstance? @Dolu1990

**Comment by numero-744** [comment]
I close it. Thanks for the report
