### ISSUE TITLE
Operator `-|` (subtraction by sat carry bit) is incorrect?

### ISSUE THREAD

**Issue by tanhongze** [SpinalHDL/SpinalHDL#725]
Substraction with saturation should get the min value.
However, in Spinal, `U(0, 2 bits) -| U(1)` would got U(3, 2 bits) instead of U(0, 2 bits).
It is saturated to max value.
Is this a bug?

**Comment by Dolu1990** [comment]
Yes you are right i think.
@jijingg 
Seems releated to https://github.com/SpinalHDL/SpinalHDL/blob/dev/core/src/main/scala/spinal/core/UInt.scala#L120
which is used by the -| operator.
Seems like we should have a specific implementation for substraction on UInt instead, right ?

**Comment by jijingg** [comment]
> Seems like we should have a specific implementation for substraction on UInt instead, right ?

yes，it' quit special ,   A specific implemetation is added to deal with this case.
