### ISSUE TITLE
How to set the init val of the reg generated by mem::readSync?

### ISSUE THREAD

**Issue by Ncerzzk** [SpinalHDL/SpinalHDL#731]
hi, I implement a simple ROM by using `Mem` , and I get the data by `readSync`.

the `readsync` would generate a reg, while I didn't find a way to set its init val, so that it would get a dirty value after reset.
(for example, if I use `getDrivingReg`, it would raise a error that the driver is not a reg)

is there a way to do this? Thank you.

my implement:
```scala
class ROM extends Component{
  // size: bytes
  // len : size/4

  val len = Config.ROM_Size/4
  val io = ROM.interfaceOfSelf
  val rom=Mem(Bits(32 bits),len).init(Array.fill(len)(B(0)))

  io.data := rom.readSync(io.addr>>2)
}
```

**Comment by kleinai** [comment]
The Mem emitters don't support resets on read sync registers. Although they should for this exact reason.

**Comment by Dolu1990** [comment]
Right, it isn't supported, mostly it may be delicate to infer and is a corner case feature.
For which kind of design do you need this feature ?

**Comment by Ncerzzk** [comment]
> 
for example, I  connected  the ROM with the IF stage of my CPU. While because the init val of reg could not be set, the IF stage would get a random value before valid instructions.

![20220516183831](https://user-images.githubusercontent.com/9284611/168575475-e572fb47-ced4-4434-8fd2-897d294b2837.jpg)

**Comment by Dolu1990** [comment]
Hmm, so one thing in practice, is that you would have some clock cycle while reset is still active. (this is kind of a common practice to ensure a few things have time to propagate)
Would that be good for you ?

**Comment by Ncerzzk** [comment]
Thank you. Sorry for my lack of practical experience for the logic design.
> you would have some clock cycle while reset is still active.
This is good for me in this case.

**Comment by Dolu1990** [comment]
No worries, I'm not saying there there is no case for the feature :)
