### ISSUE TITLE
StreamCCByToggle bug when using clock enable 

### ISSUE THREAD

**Issue by Hiyori97** [SpinalHDL/SpinalHDL#736]
The clock enable of outputClock in StreamCCByToggle is not applied correctly.
If the outputClock uses an enable, such as SlowArea, data will be a loss, as in the following example.

```scala
class Demo extends Module {
  val inStream = slave Stream Bits(8 bits)
  val outStream = master Stream Bits(8 bits)
  val inClkDomain = ClockDomain.current
  val outArea = new SlowArea(4) {
    outStream <-< inStream.ccToggle(inClkDomain, ClockDomain.current)
    ClockDomain.current.clockEnable.simPublic()
  }
}

object Demo extends App {
  SpinalSimConfig().compile(new Demo).doSim { dut =>
    dut.clockDomain.forkStimulus(20)

    var num = 0
    def seqNumber(payload: Bits) = {
      payload #= num
      num += 1
      true
    }
    val drv = StreamDriver(dut.inStream, dut.clockDomain)(seqNumber)
    drv.transactionDelay = () => 0

    dut.outStream.ready #= true
    StreamMonitor(dut.inStream, dut.clockDomain)(p => print(s"in data ${SimData.copy(p)}"))
    StreamMonitor(dut.outStream, dut.outArea.clockDomain)(p => print(s"out data ${SimData.copy(p)}"))

    dut.clockDomain.waitActillveEdge(100)
    // print
    // in data self : 0x0
    // in data self : 0x1
    // out data self : 0x0
    // in data self : 0x2
    // in data self : 0x3
    // out data self : 0x2
    // in data self : 0x4
    // in data self : 0x5
    // out data self : 0x4
    // in data self : 0x6
    // in data self : 0x7
    // out data self : 0x6
    // ...
  }
}
```

----------

asyncAssertSyncDeassertCreateCd removes clock enable from outputClock; so pop.valid and pop.hit in StreamCCByToggle do not contain clock enable

https://github.com/SpinalHDL/SpinalHDL/blob/be0efd2f6a3d77f9d3138e3745e31802c4756c8d/lib/src/main/scala/spinal/lib/Stream.scala#L1348-L1356

https://github.com/SpinalHDL/SpinalHDL/blob/141dae6153b43d544422daea6caaab9b04d883d7/lib/src/main/scala/spinal/lib/Utils.scala#L1222-L1235

https://github.com/SpinalHDL/SpinalHDL/blob/f8f375e2ec7aba1e67025eeccd22f647c7ecd854/lib/src/main/scala/spinal/lib/CrossClock.scala#L122-L136

**Comment by Dolu1990** [comment]
Thanks, nice catch ^^
Just fixed it.
