### ISSUE TITLE
when clause seems not friendly to functions.

### ISSUE THREAD

**Issue by Readon** [SpinalHDL/SpinalHDL#743]
I used a function in when clause like:
``` scala
val input = UInt()
input := U(8)
when(ax.valid) {
   foo() // in foo input has been assigned again.
}
```
Then assignment overlap error reported and fail the elaborating.

**Comment by Dolu1990** [comment]
what is foo() about ?

**Comment by Readon** [comment]
> what is foo() about ?

emmm, foo() is a method of bundle object.
in foo() there are still logics with or without when clauses.

**Comment by Dolu1990** [comment]
Can you provide a fully self contained example ?
I'm realy not sure how to reproduce

**Comment by Readon** [comment]
I have test it again it's not a problem.
