### ISSUE TITLE
A strange behaviour in `Delay`

### ISSUE THREAD

**Issue by wswslzp** [SpinalHDL/SpinalHDL#754]
Say we have a module as follows
```scala
  case class P10() extends Module {
    val a = in Bool()
    val clear = in Bool()
    val b = out Bool()

    b := DelayWithInit(a, 4){d=>
      println(d.getBitsWidth)
    }
  }
```
This module creates a four-stage pipeline on input `a` and prints the bit width of each pipeline register. SpinalHDL will generate this module properly.
However, if we change `DelayWIthInit` into `Delay` as follows
```scala
  case class P10() extends Module {
    val a = in Bool()
    val clear = in Bool()
    val b = out Bool()

    b := Delay(
      a, 4,
      onEachReg = (d: Bool)=> {
        println(d.getBitsWidth)
      }
    )
  }
```
Then, SpinalHDL (v1.7.0) will report a null pointer error and after debug `b` turns out to be `null`. I'm kind of confused by this problem.

**Comment by Dolu1990** [comment]
Delay[Bool] fix the initial weird bug, i don't know why

I think DelayWithInit is the workaround, it allows much shorter writing by using currying to solve the type of the apply function : 

```scala
    b := DelayWithInit(a, 4){d =>
      println(d.getBitsWidth)
    }
```

**Comment by wswslzp** [comment]
I tried to modify the `Delay` function signature from original 
```scala
def apply[T <: Data](that: T, cycleCount: Int,when : Bool = null,init : T = null.asInstanceOf[T],onEachReg : T => Unit = null.asInstanceOf[T => Unit]): T = {
```
to this version without `asInstanceOf`
```scala
def apply[T <: Data](that: T, cycleCount: Int, when : Bool = null, init: T = null, onEachReg : T => Unit = null): T = {
```
then the bugs disappeared. 
It's maybe a bug from scala.

**Comment by wswslzp** [comment]
In addition, `DelayWithInit` can be implemented as another `apply` function of `Delay`, I think. The `DelayWithInit` function can do much more than just initialization.

**Comment by Dolu1990** [comment]
> The DelayWithInit function can do much more than just initialization.

Right 

> asInstanceOf

ahh weird, i remember that in general, i had issue with null vs [T] throwing compilation errors without the asInstanceOf XD

For intance init : T = null.asInstanceOf[T]  without it, => compilation error  on my side

I pushed thefix for the onEachReg, thanks ^^
