### ISSUE TITLE
[Feature Request] AFix implement traits `Num[AFix]` and `MinMaxProvider` 

### ISSUE THREAD

**Issue by wswslzp** [SpinalHDL/SpinalHDL#766]
Hi @kleinai ,

`AFix` is an amazing work and a great contribution! Unified fixed-point data type makes my development easier! 
I'm now working on writing a generic algorithm library that takes a generic data type that supports some basic arithmetic operations, that is `Num` trait. 

If `AFix` implements such `Num` trait, my algorithm library can apply to not only UInt/SInt, but also AFix. Likewise, some other traits `BitWiseOp` and `MaxMinProvider` can also be implemented by AFix.

**Comment by kleinai** [comment]
Tracked by #767
