### ISSUE TITLE
load repeat data when use loadBinary

### ISSUE THREAD

**Issue by aiit-linry** [SpinalHDL/SpinalHDL#778]
https://github.com/SpinalHDL/SpinalHDL/blob/703a281be9fc1e918e1f49431e3e22591b561c2c/lib/src/main/scala/spinal/lib/bus/amba4/axi/sim/AxiMemorySim.scala#L142

When the length over one page, data should be cut to slice. But use drop() in this line is error, data wont drop itself. This function should like this:

var data_temp = data
...
...
for(xx){
..
val bytesWritten = page.writeArray(offset, data_temp)
data_temp = data_temp.drop(bytesWritten)
..
}

**Comment by aiit-linry** [comment]
scala version: 2.11.12

**Comment by hanm2019** [comment]
I found the same problem, and pull a merge request #784

**Comment by aiit-linry** [comment]
> @aiit-linry You can test again on `dev` branch

test pass in 1.7.2, thx
