### ISSUE TITLE
It's best to put SpinalFormalFunSuite.scala into lib or sim to help project test with formal.

### ISSUE THREAD

**Issue by Readon** [SpinalHDL/SpinalHDL#797]
The existing SpinalFormalFunSuite is a wrap of FunSuite for formal verification.
However, this can only be used to verify SpinalHDL itself.
Move SpinalFormalFunSuite to lib or sim subproject to provide the accessibility of projects using Spinal is necessary.

The problem is where to put this file. 
It seems that lib subproject is not suitable for test related code.
However, sim subproject is also not very fit for that, because it's mainly target to simulation.

**Comment by Dolu1990** [comment]
Ahh why not :)
spinal.lib.formal i would say is a good place

**Comment by Readon** [comment]
> Ahh why not :) spinal.lib.formal i would say is a good place

That would lead to the dependency of org.scalatest.
