### ISSUE TITLE
inout error in 1.7.1, it's ok in 1.7.0

### ISSUE THREAD

**Issue by yuqi-ali** [SpinalHDL/SpinalHDL#807]
`import spinal.lib._
import spinal.core._
case class A() extends BlackBox{
  val a=inout(Analog(Bool()))
  val b=inout(Analog(Bool()))
  val c= out Bool()
}
case class Port() extends Bundle with IMasterSlave {
  val a=inout(Analog(Bool()))
  val b=inout(Analog(Bool()))
  val c= Bool()

  override def asMaster(): Unit = {
    out(c)
  }
}

case class C() extends Component{
  val port=master(Port())
  val aInst=A()
  aInst.a<>port.a
  aInst.b<>port.b
  aInst.c<>port.c
}

case class D() extends Component{
  val port=master(Port())
  val cInst=C()
  port<>cInst.port
}

object BApp extends App{
  SpinalSystemVerilog(D())
}`

**Comment by Dolu1990** [comment]
Stupid mistake ^^
