### ISSUE TITLE
Fail on access counter in withTimeOutAsserts.

### ISSUE THREAD

**Issue by Readon** [SpinalHDL/SpinalHDL#818]
When doing prove, it's necessary to sync the counter value of two interface checker. 
However, the existing withTimeOutAsserts below could not provide access to the counter.
  ``` scala
  def withTimeoutAsserts(maxStallCycles : Int = 0) : this.type = {
    import spinal.core.formal._
    if (maxStallCycles > 0) {
      val counter = Counter(maxStallCycles, this.isStall).setCompositeName(this, "timeoutCounter", true)
      when(!this.isStall) { counter.clear()} 
      .otherwise { assert(!counter.willOverflow) }
    }
    this
  }

 val timeChecker = output.r.withTimeoutAsserts(8) //timeChecker could not access the counter so that the synchronization is impossible.
```

So in formal verification, almost all register should be accessible, due to the nature of k-induction is to set all registers to value do not disobey the assertions.

I think there should be a good pattern to write formal facilities.
The way I used now in Axi4ReadOnly is to add a formalContext function which provide necessary accessible regs and error signals, then use withAsserts to do the assertion and withAssumes for assumptions.
The drawback is that formalContext has to be called once and only once before withAsserts.

Is there any good way to make it elegant?

**Comment by Dolu1990** [comment]
> Is there any good way to make it elegant?

I would say in general you can make the function returning an area with all its content :
```scala
def withTimeoutAsserts(maxStallCycles : Int = 0) = new Area {
  import spinal.core.formal._
  val logic =  (maxStallCycles > 0) generate new Area{
    val counter = Counter(maxStallCycles, this.isStall).setCompositeName(this, "timeoutCounter", true)
    when(!this.isStall) { counter.clear()} 
    .otherwise { assert(!counter.willOverflow) }
  }
}
```

Would that help ?
