### ISSUE TITLE
[Feature Request] `Counter` and `CounterUpDown` need a way to set non-zero reset value. 

### ISSUE THREAD

**Issue by wswslzp** [SpinalHDL/SpinalHDL#823]
In some cases, after asserting reset a counter returns to a non-zero value or a value between start and end. But in the current SpinalHDL, counter infra didn't provide such feature yet.

**Comment by Dolu1990** [comment]
Ahhh so having a paramter to set the reset value ?

**Comment by wswslzp** [comment]
Yes

**Comment by Dolu1990** [comment]
I pushed a way to set the init value of the Counter.

For instance : 
val miaou = Counter(3,9) init(5)

**Comment by Dolu1990** [comment]
same for UpDown

**Comment by wswslzp** [comment]
Thanks a lot :)
