### ISSUE TITLE
Vivado: Pass flags to `xelab` and `xsim`, or allow to load custom `tcl` script

### ISSUE THREAD

**Issue by dzx-dzx** [SpinalHDL/SpinalHDL#837]
Some IP cores from Xilinx detect a macro to alter its behavior, such as shortening simulation time. And there's a flag called `verilog_define` to apply the desired macro when compiling. But neither does SpinalHDL support passing flags(I guess?), nor can it take a custom simulating script as a workaround.

**Comment by kleinai** [comment]
What sort of flags do you need and where? As part of the `xelab` command?
We could also make space for custom commands before the sim script generation is run in Vivado.

**Comment by dzx-dzx** [comment]
> As part of the `xelab` command

Ah yes. `-d` specifically.

**Comment by dzx-dzx** [comment]
> We could also make space for custom commands before the sim script generation is run in Vivado.

I reckon that can work too, by utilizing `set_property verilog_define`.
