### ISSUE TITLE
AxiMemorySim could not simulate continuous read.

### ISSUE THREAD

**Issue by Readon** [SpinalHDL/SpinalHDL#839]
The waveform shows that there is an extra idle cycle of data channel's valid, so that the root cause is from AxiMemorySim.
I think it is caused by [this line](https://github.com/SpinalHDL/SpinalHDL/blob/6e128db5ac0a1a7a109439503037108f53fc850b/lib/src/main/scala/spinal/lib/bus/amba4/axi/sim/AxiMemorySim.scala#L404).
There exist one extra waiting sample after one transaction.
It should be moved to "else" block when "pending_reads" is empty.

**Comment by Readon** [comment]
It's also necessary to carefully discuss on straight forward waitSampling in each handles, like [this](https://github.com/SpinalHDL/SpinalHDL/blob/6e128db5ac0a1a7a109439503037108f53fc850b/lib/src/main/scala/spinal/lib/bus/amba4/axi/sim/AxiMemorySim.scala#L469).

**Comment by Dolu1990** [comment]
hmmm Idealy, it should not use the blocking sim API, as it is way slower than callback based API (onSampling)
I would say, it should have ben based on the StreamMonitor / StreamDriver.

**Comment by Readon** [comment]
> 



> hmmm Idealy, it should not use the blocking sim API, as it is way slower than callback based API (onSampling) I would say, it should have ben based on the StreamMonitor / StreamDriver.

I would find time to fix this. However, I do not have write channel related test code at hand now. So it will take some time.
We might remain this issue open, and rework on the code later.
