### ISSUE TITLE
Add timeout option to `ClockDomain.waitSamplingWhere()`?

### ISSUE THREAD

**Issue by jonnykl** [SpinalHDL/SpinalHDL#859]
I think it could be useful to have an optional timeout option when waiting for an event which might not occur. Maybe you want to check the given condition is not satisfied for the next n clock cycles. Therefore it is not possible to use `SimTimeout` there. `waitSamplingWhere()` could return a `boolean` indicating whether the timeout has occurred or not.

What do you think?

**Comment by Dolu1990** [comment]
hmmm, yes, why not :)

**Comment by Dolu1990** [comment]
Added in https://github.com/SpinalHDL/SpinalHDL/commit/68d375a1921b5460d7fee0c051336872df76dd3d

**Comment by jonnykl** [comment]
nice!
