### ISSUE TITLE
RegNextWhen issue

### ISSUE THREAD

**Issue by wel97459** [SpinalHDL/SpinalHDL#867]
I'm having a worried issue when using RegNextWhen and getting an error:

[spinalerr.txt](https://github.com/SpinalHDL/SpinalHDL/files/9611934/spinalerr.txt)
`
line 31: val CMD_Reg = RegNextWhen(io.DataIn, !io.N3_ && io.TPB, Bits(8 bits)) init(0x80)
`

If I write the same statement using:
`
val value = Reg(Bits(8 bits)) init(0x80)
 when(!io.N3_ && io.TPB){ CMD_Reg := io.DataIn }
`
I don't get any errors.
And there is only one clock domain.

**Comment by Dolu1990** [comment]
Hi,

`val CMD_Reg = RegNextWhen(io.DataIn, !io.N3_ && io.TPB) init(0x80)` should be good
So the third parameter you have in the RegNextWhen is the issue, it is used as reset value, and is never specified with a value (just a new undriven signal Bits(8 bits))

**Comment by wel97459** [comment]
Oh that makes sense, thanks for the help!
