### ISSUE TITLE
Way too big signal issue

### ISSUE THREAD

**Issue by cheerryio** [SpinalHDL/SpinalHDL#870]
I have the need to define a signal of large width(which is bigger than 4096), but I get this error ```Way too big signal (toplevel/InWrBufData : in Bits[5120 bits])```. How am I able to disable this phase check "PhaseInferWidth"?

**Comment by Dolu1990** [comment]
Hi, i pushed a open in dev : 

SpinalConfig(bitVectorWidthMax = 5000).generateVerilog( ... )
Should be good ^^
