### ISSUE TITLE
Feature: UIntToOh for faster simulation?

### ISSUE THREAD

**Issue by tanhongze** [SpinalHDL/SpinalHDL#873]
Now, `UIntToOh` is implemented as
```
  def apply(value: UInt, width : Int): Bits = {
    val ret = Bits(width bits)
    for(i <- 0 until width){
      ret(i) := value === i
    }
    ret
  }
```
By using an alternative implement, we could make this simulation much faster(with no impact to synthesis):
```
  def apply(value: UInt, width : Int): Bits = {
    B(1, width bits) |<< value
  }
```

**Comment by numero-744** [comment]
Can you open a PR, please? Else I can do it.

**Comment by andreasWallner** [comment]
Out of curiosity, with which synthesis toolset did you compare the two?
This kind of reminds me of this blog entry: https://andy-knowles.github.io/one-hot-mux/ where Andy Knowles compared multiple HDL implementations of OH encoders.

**Comment by tanhongze** [comment]
I just tested it under Vivado.
For a 5-32 decoder 10-1024 decoder, these implementations of `UIntToOh` would be mapped to exactly same synthesized design. (Thus, same net delay and same logic delay)

**Comment by Dolu1990** [comment]
Merged
