### ISSUE TITLE
TupleBundle error when use in Mem

### ISSUE THREAD

**Issue by yportne13** [SpinalHDL/SpinalHDL#887]
Mem use asBits and assignFromBits, so when only override def asBits and forget to give a matched assignFromBits, the data read from mem will go wrong. TupleBundle only override def asBits so it goes wrong

**Comment by Dolu1990** [comment]
Ahhh damned, i didn't event knew that TupleBundle was big endian :/

I just pushed a fix which reverse the internal storage directly instead of patching functions.
