### ISSUE TITLE
Assignment problem

### ISSUE THREAD

**Issue by balanx** [SpinalHDL/SpinalHDL#890]
Environment : JDK 18, scala-2.12.16, sbt-1.7.1, spinalhdl 1.7.2

=== code begin ===
import spinal.core._
import spinal.lib._

case class Test() extends Component {
  var u = UInt(8 bits)
  u \\= (3->false, default -> true)
}
=== code  end  ===

[error] D:\temp\test\test.scala:9:5: value \= is not a member of spinal.core.UInt
[error]   Expression does not convert to assignment because:
[error]     too many arguments (2) for method \: (that: spinal.core.UInt)spinal.core.UInt
[error]     expansion: Test.this.u = Test.this.u.\(3.$minus$greater(false), default.$minus$greater(true))
[error]   u \\= (3->false, default -> true)
[error]     ^
[error] one error found
[error] (Compile / compileIncremental) Compilation failed

**Comment by Readon** [comment]
use "u :=" instead. 
and "val u" is preferred, not "var u".

**Comment by Dolu1990** [comment]
Also yes, i agree with Readon, in general, never use the \= operator, unless you want to do carry chaine/priority like stuff.

**Comment by numero-744** [comment]
@balanx is it okay for you?

**Comment by balanx** [comment]
OK.
Thanks Readon. Thanks Dolu. Thanks numero !
