### ISSUE TITLE
Suggestion of labels for development flow / issue & doc management

### ISSUE THREAD

**Issue by numero-744** [SpinalHDL/SpinalHDL#899]
* issues start with "bug" or "idea" or "feature"
* "idea" can become "feature" when an API is defined
* "doc required" when no scaladoc OR (missing RTD AND no tracking issue in RTD)
* "doc required" for PRs too, blocking to merge
* need more people with rights to manage labels, to keep them up to date

**Comment by Dolu1990** [comment]
Yes currently label are underused, could be extended.
About having more people, recently a few additional maintainers were added, but so far, nobody is "full time" on SpinalHDL.

**Comment by numero-744** [comment]
Labels updated
