### ISSUE TITLE
breaking changes in sim/Agent api

### ISSUE THREAD

**Issue by numero-744** [SpinalHDL/SpinalHDL#923]
```diff
-def onWriteByte(address: BigInt, data: Byte): Unit
+def onWriteByte(address: BigInt, data: Byte, id: Int): Unit
-def onLast(id: Int): Unit
```

Reported by @Readon
Assigned to @kleinai

**Comment by numero-744** [comment]
Introduced by https://github.com/SpinalHDL/SpinalHDL/pull/821/commits/18033becfe533b56b55673c5a34909f3ce940828

Suggested changes:

```diff
+def onWriteByte(address: BigInt, data: Byte): Unit
-def onWriteByte(address: BigInt, data: Byte, id: Int): Unit
+def onWriteByte(address: BigInt, data: Byte, id: Int): Unit = onWriteByte(address, data)
```

**Comment by Readon** [comment]
one more thing is about onLast, which has been removed.

**Comment by numero-744** [comment]
Meta notes:

* Knowing what these functions do could help during the PR review process, to understand why they can / should (well, in this case, shouldn't) be removed or changed. But they are undocumented :rainbow:
* Breaking API changes without a deprecation period is painful, IMHO more than switching to auto-formatting on a file-by-file basis XD

**Comment by kleinai** [comment]
My bad. I had constructed the unburster and ID remover components as part of a larger Axi4 to AxiLite4 change set and I needed a lot more sim agent features. Fix is in PR.
