### ISSUE TITLE
Add gray encoding to Enum encodings

### ISSUE THREAD

**Issue by numero-744** [SpinalHDL/SpinalHDL#939]
Useful for FSM

**Comment by Dolu1990** [comment]
Hooo right. Never thinked about it ^^

**Comment by andreasWallner** [comment]
I thought about that a while ago, but: If I want an grey encoded FSM I'd like that all state transitions only change 1 bit in the state variable. When I thought about implementing this I could not find a way to get a list of all transitions to try to map the states accordingly (and error out if simply not possible).
Did I overlook something there?

**Comment by numero-744** [comment]
In #730 I mention "gray" and "gray-like" encodings.

Gray encoding (discussed in current issue) is KISS:

* it just performs gray encoding in the order variants (or states) appear
* it is generic (for Enum, not specific to FSM)
* it is optimal for an FSM which just cycles the states in the order they are defined, and does not need to understand the FSM transitions, so the user can easily know the actual encoding of each value and for a more complex FSM to make decisions.

Gray-like encoding is more complex, and I have not opened an issue for it since I am not sure it is possible to do without doing complex things (that can break more easily):

* it would optimize the encoding for the specific FSM to have the less bit flips possible
* it would be specific to FSM (would not be possible to use it directly on Enum)

But there is an issue with gray-like encoding: how could the static analysis tell that such transition (`goto`) is used more than another one? It would require run-time profiling, so it would require the user to provide tests that "look like" the real use-case. Also, it could give the user a feel to get something optimized but maybe it is not (I guess something OH is better?).

**Comment by kleinai** [comment]
How about adding hints into the FSM to tell it how to optimize the encoding if desired?

**Comment by Readon** [comment]
emmm, if I understand correctly is this possible to implement a gray encoding FSM?
``` scala
      val fsm = new StateMachine{
        setEncoding(
          IDLE -> toGray(0),
          STATE_A -> toGray(1),
          STATE_B -> toGray(3),
          STATE_C -> toGray(7),
          stateBoot -> toGray(15)
        )
     }
```
Of course, one more step is required to override the existing toGray object's apply method to fit the type.

**Comment by andreasWallner** [comment]
@numero-744 understood, I guess if it e.g. called `graySequential` or something it might be obvious enough that there are limitations. In some locations we depend on gray encoding for clock domain crossing, a mess up there wouldn't be nice (but I guess there should then anyhow be a test/assert/proof in the user code as well ;-))

I'll dump this here for now, that was my code when I last thought about it:
```scala
object graySequential extends SpinalEnumEncoding {
  private def gray2binary(gray: BigInt): Int = {
    assert(gray.bitLength <= 16, "conversion currently only implemented for <= 16 bit")
    var tmp = gray ^ (gray >> 8)
    tmp ^= tmp >> 4
    tmp ^= tmp >> 2
    tmp ^= tmp >> 1
    tmp.toInt
  }
  override def getWidth(e: SpinalEnum): Int = log2Up(e.elements.length)
  override def getValue[T <: SpinalEnum](element: SpinalEnumElement[T]): BigInt = (element.position >> 1) ^ element.position
  override def getElement[T <: SpinalEnum](element: BigInt, enums: T): SpinalEnumElement[T] = enums.elements(gray2binary(element))
  override def isNative = false
  setName("graySeq")
}
```
I'll open a PR if this is what you had in mind.

**Comment by numero-744** [comment]
Yes this is the idea for KISS gray encoding :smiley: 

Btw I guess it would be native (i don't know what it means tbh)?

**Comment by andreasWallner** [comment]
I'd have guessed that only the "native" encoding is native (https://github.com/SpinalHDL/SpinalHDL/blob/4b8480138879e403310f666116abc55c32707054/core/src/main/scala/spinal/core/Enum.scala#L317)

**Comment by Dolu1990** [comment]
> Therefore maybe it would be nice to have it defaulting to false in SpinalEnumEncoding, and to override it only in native (and in inferred too?).

Yes that's right.
i just pushed it.
