### ISSUE TITLE
Generate gtkwave files

### ISSUE THREAD

**Issue by numero-744** [SpinalHDL/SpinalHDL#958]
I often need the same waves on several tests, using gtkwave. To save the waves that were displayed, I save a `.gtkw` file.

I run all my tests, then for a failing test I open gtkwave with the `.gtkw` file. But to do this I need to edit this file to change the data file to open, depending on the test which failed.

A feature could be to choose to generate automatically a `.gtkw` file for each test run (taking a sequence of signals / separators?), and then open for instance failing tests only, or all tests?

Another (maybe simpler) way to do could be to be able to change in a user's `.gtkw` file the path of the data file and open it (derivation of a user file built with gtkwave instead of generating a new one)? This way the user benefits from gtkwave's GUI and it manages all the options of gtkwave with lightweight implementation?

Maybe it is too niche, what do you think about it?

**Comment by numero-744** [comment]
If we don't implement it in Spinal I'll maybe just write a simple `sh` script for derivation XD

**Comment by numero-744** [comment]
Use case:

I have run a simulation with two tests:

- `doSim("empty")` generating `simWorkspace/Aes/empty.fst`
- `doSim("tests")` generating `simWorkspace/Aes/tests.fst`

I have a `gtkw` folder at the root of the project, with all my `.gtkw` files created with GtkWave's UI. Among them, `gtkw/Aes.gtkw`, created by opening one of the `.fst` files above, adding waves, and saving.

To generate files, I run:

```sh
deriveGtkw gtkw/Aes.gtkw simWorkspace/Aes/*.fst
# deriveGtkw <source> <wave files...>
```

It creates:

- `simWorkspace/Aes/empty.fst.gtkw`
- `simWorkspace/Aes/empty.fst.gtkw`

But these files are deleted on next simulations…

I create directory `gtkw/Aes` and I run:

```sh
deriveGtkw gtkw/Aes.gtkw gtkw/Aes simWorkspace/Aes/*.fst
# deriveGtkw <source> <target dir> <wave files...>
```

It creates:

- `gtkw/Aes/empty.fst.gtkw`
- `gtkw/Aes/tests.fst.gtkw`

---

Below is `deriveGtkw`

```sh
#!/bin/sh

if [[ $# < 2 ]]; then
        echo "Bad usage" >&2
        echo "$0 source.gtkw [outdir] wavefiles"
        exit 2
fi

src=$1
shift

outdir=""
if [ -d "$1" ]; then
        outdir="$1"
        shift
fi

replace() {
        while read -r l; do
                if [[ $l = \[dumpfile\]* ]]; then
                        # Caution: no chasing (for instance for `"`)
                        echo "[dumpfile] \"$1\""
                else
                        echo "$l"
                fi
        done < $src
}

for f in "$@"; do
        outf="$f.gtkw"
        if [ -n "$outdir" ]; then
                outf="$outdir/$(basename "$f").gtkw"
        fi
        if [ -r "$f" ]; then
                replace "$(realpath "$f")" > "$outf"
        else
                echo "Can't open '$f', aborting" >&2
                exit 1
        fi
done
```

**Comment by wswslzp** [comment]
Just keep things simple

**Comment by numero-744** [comment]
Wondering: do you think it is worth documenting it somewhere? I mean, I can't evaluate the situation XD

* maybe someone crazy enough to want to do such a thing will implement their own thing and have fun doing it as I did.
* maybe someone crazy enough to want to do such a thing will try to open an issue, and before that looking for similar issues and founding this one.
* maybe it is actually useful to add waves in regression tests for debugging and being able to quickly go from one test to another one.

**Comment by wswslzp** [comment]
I don't think this can be called 'crazy' XD. In ASIC workflow there are tons of scripts using bash/Perl/Python doing dirty things like this.

**Comment by numero-744** [comment]
So maybe we can add a page for instance at the end of the Simulation part of RTD with this piece of code and an example of use?

**Comment by wswslzp** [comment]
I mean, is this has anything to do with SpinalHDL? Maybe putting this code in GTKWave repo/doc is even more reasonable.

**Comment by numero-744** [comment]
Ooh, good idea! I'll ping them
