### ISSUE TITLE
Deprecate Bool function with no braces

### ISSUE THREAD

**Issue by numero-744** [SpinalHDL/SpinalHDL#972]
I'm still not sure I understand why, but @Dolu1990 said it was not a good thing.

- [x] Deprecate `Bool`, should use `Bool()` instead
- [x] Check no deprecated syntax is in this repository
- [x] Check no deprecated syntax in RTD

**Comment by Dolu1990** [comment]
The reason main reason is scala compatibility / scala 2.13 / scala 3.x
Also, Bool alone has sometime some surprising scala compilation XD

**Comment by Dolu1990** [comment]
@Readon For all scala versions where we can keep Bool without () working, we will keep it. So existing projects will not break.
This is only to warn about it.

**Comment by Readon** [comment]
> 

That would be good.
