### ISSUE TITLE
Test failed while running spinal.tester on MSys2 environment.

### ISSUE THREAD

**Issue by Readon** [SpinalHDL/SpinalHDL#973]
it reported that charset exception.

**Comment by Readon** [comment]
@kleinai could you please check about the get_time_precision please? If you have Msys2 environment, can you help to test that?

**Comment by kleinai** [comment]
I can't get sbt to run correctly on msys. Maybe it's because I tried using my normal openJDK install. I had a hard time finding a guide.

Could you report what sim and version you're encountering this error on?

**Comment by Readon** [comment]
> I can't get sbt to run correctly on msys. Maybe it's because I tried using my normal openJDK install. I had a hard time finding a guide.
> 
> Could you report what sim and version you're encountering this error on?

1. I am using latest MSys2 tools with Yosys and SymbiYosys packages build by myself.
2. installed java through [SDKMAN](https://sdkman.io/) by "sdk install java 8.0.352-tem".
3. The cocotb is installed by "pip install cocotb".
4. The SpinalHDL is the latest version in dev branch with PR #969 and #974.

files for yosys and symbyosys is attached here.
[Tools.zip](https://github.com/SpinalHDL/SpinalHDL/files/10072325/Tools.zip)

**Comment by Readon** [comment]
> sdkman is a nice experience. However my msys2 sbt is still looking in `C:\...` and not `/c/...` and I think that's hanging it up from booting a build. I'm trying to compile a jdk in msys2 to see if that fixes it.

Sorry, I forgot to put the argument that I started msys2. 
here is the command use can apply in your terminal, like Windows Terminal "xxxx/msys64/msys2_shell.cmd -defterm -here -no-start -mingw64".
You can avoid Windows environment variable by avoid use argument "-use-full-path".

**Comment by Readon** [comment]
If you want to use sbt, then it is possible to install it while "sdk install sbt".

**Comment by kleinai** [comment]
My intellij launches are using simulators out of msys64. That should be sufficient?

**Comment by Readon** [comment]
I tried to initial the vscode in the standalone msys2 environment by absolute path, and it works.
I could try IntelliJ IDEA too.

**Comment by kleinai** [comment]
That sim time precision function isn't doing anything out of the ordinary. My guess is that your simulator version might not support it?
I have `Verilator 4.218 2022-01-17 rev UNKNOWN.REV`

**Comment by Readon** [comment]
My verilator version is mingw-w64-x86_64-verilator 5.002-1 (mingw-w64-x86_64-eda)

**Comment by Readon** [comment]
> That sim time precision function isn't doing anything out of the ordinary. My guess is that your simulator version might not support it? I have `Verilator 4.218 2022-01-17 rev UNKNOWN.REV`

It reports UnsatifiedLinkError which seems related to the loadLibrary mechanism.

**Comment by kleinai** [comment]
I wonder if the problem isn't with the time precision function but only because that's the first native function called?

**Comment by Readon** [comment]
> but only because that's the first native function called?

EMM, I suspect about that before, however, other tests have passed.

**Comment by kleinai** [comment]
If you set that line to 1 and comment out the function call is it any different? The passing tests should still pass.

**Comment by Readon** [comment]
does the generate-cxx.sh file been called and generate swig interface class automatically?



---Original---
From: "Aidan ***@***.***&gt;
Date: Wed, Nov 23, 2022 12:03 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [SpinalHDL/SpinalHDL] Test failed while running spinal.tester onMSys2 environment. (Issue #973)




 
If you set that line to 1 and comment out the function call is it any different? The passing tests should still pass.

**Comment by Readon** [comment]
I found the problem.
It is caused by the cache files generated by previous sbt building.
it now works.

**Comment by Readon** [comment]
> I found the problem. It is caused by the cache files generated by previous sbt building. it now works, thanks.

The final solution is to clean the class file generate by java compiler in simWorkspace. or just delete the sim directory.

**Comment by kleinai** [comment]
Maybe we need to be more aggressive when handling the sim cache?

**Comment by Readon** [comment]
> Maybe we need to be more aggressive when handling the sim cache?

The sim cache belongs to user's project.
As a lib, we could not do much on that. It might confuse them.
