### ISSUE TITLE
A problem with switching SV syntax to SpinalHDL syntax

### ISSUE THREAD

**Issue by Shiyunfeng96** [SpinalHDL/SpinalHDL#999]
Hello, I am currently developing a project based on SpinalHDL. I have a problem with syntax.

the SV:
`   wire   [7:0]  string_mode; 
if ((match_data_vld == 1'b1) && (d_set[m][string_mode[5:0]] == 1'b1){
    xxxxxxx
 }`

the SpinalHDL:
val string_mode = UInt(8 bits)
`when((match_data_vld === 1) && (d_set(m)(string_mode) == 1)
`

This seems to generate some errors
the **string_mode** cannot be applied to (Int)！

do i miss someting？

**Comment by Readon** [comment]
> the SpinalHDL: val string_mode = UInt(8 bits) `when((match_data_vld === 1) && (d_set(m)(string_mode) == 1) `
                                                                                                                                                                            ^^^ Can you try to append one more "=" to here?

**Comment by numero-744** [comment]
Closed as there was no answer from issue author in the last weeks. Feel free to reopen the issue if you still need help.
